### ISSUE TITLE
Use modern logging framework

### ISSUE THREAD

**Issue by englishman** [spring-projects/spring-integration#1782]
Currently [Apache Commons Logging](http://commons.apache.org/proper/commons-logging/) is used in Spring Integration project.

Unfortunately, this framework looks like a bit obsolete (the last update is in 2014). Also e.g. in `org.springframework.integration.channel.interceptor.WireTap` I see this code:
```java
if (!sent && logger.isWarnEnabled()) {
	logger.warn("failed to send message to WireTap channel '" + this.channel + "'");
}
```
What is wrong here?
1. direct current logging status check via `logger.isWarnEnabled()` 
2. using String concatenations in `logger.warn(...)` makes logging messages unclear

Modern logger frameworks (e.g. [slf4j](http://www.slf4j.org/)) allows to implements this logic in more smart way:
```java
if (!sent) {
	logger.warn("failed to send message to WireTap channel '{}'", this.channel);
}
```
The advantages are
1. no more direct logging status checks
2. logging messages are clear and ready for _i18n_

**Comment by artembilan** [comment]
@englishman ,

thank you for report!

Please, read these two articles:
https://spring.io/blog/2009/12/04/logging-dependencies-in-spring
https://spring.io/blog/2015/12/03/spring-framework-5-0-roadmap-update
and comments to them.

No one stops you to use any logging framework in your application.
But we develop here a library, framework which is based on some other our foundation (Spring Framework?) and for consistency all our projects follow the same dependencies and internal model rules. And with the Core Spring Framework foundation and our extensions we keep the same model and won't break anything in our code, if we'd switch to something else otherwise.

Even more. Some modern our projects have started to switch from `SLF4J` to `JCL` back. Exactly for the reason to meet consistency and compatibility with the Core project.

So, those all features like `i18n` are good and known for us, but we won't switch to any other logging framework until the Core one does that.

I'm just waiting for your feedback and close the ticket after that. 
It won't be implemented. Sorry.

**Comment by englishman** [comment]
@artembilan 
I've just revised the links. You can close this issue. Thanks!
