### ISSUE TITLE
ZeroMQ

### ISSUE THREAD

**Issue by Mwea** [spring-projects/spring-integration#1840]
Hi ! 
I'd like to make my own implementation of ZeroMQ for spring integration but can't find any guide or clear information on your documentation of how I'm supposed to do it or even to test. 
I've understand that the main parts of doing such implementation is to code : 
- an Inbound Channel Adapter
- an Outbound Channel Adapter
- an OutBound Gateway 

But in some projects I can find some other classes like : 
- InboundGateway
- PublishingMessageHandler

Can you explain me what are the goal of these ones ? Do I need it for my  own implementation ?

**Comment by artembilan** [comment]
See https://jira.spring.io/browse/INT-3045 on the matter.

I'd be glad to move discussion in the matter there instead.

But to save some time I'll finish this comment properly.

Well, I'd suggest you to take a look into [spring-integration-mqtt](https://github.com/spring-projects/spring-integration/tree/master/spring-integration-mqtt/src/main) module structure, since that one is similar by the Messaging principles. 
Right, you need here `Inbound Channel Adapter` and `Outbound Channel Adapter` (we can consider Outbound Gateway or even Inbound eventually), but that is a high level abstraction. From the API perspective you have to write `MessageProducer` and `MessageHandler` classes for inbound and outbound parts, respectively.
See more info here: http://docs.spring.io/spring-integration/docs/4.3.0.RELEASE/reference/html/overview.html#programming-tips

**Comment by artembilan** [comment]
See #2343 

Also closed in favor of https://jira.spring.io/browse/INT-3045.
