### ISSUE TITLE
AbstractStompSessionManager.connect() Null Pointer Exception

### ISSUE THREAD

**Issue by dagan** [spring-projects/spring-integration#1854]
As of https://github.com/spring-projects/spring-integration/commit/1cc1b2ef79cd5742c65bc5163261e7b4db80ccb2#diff-66c0257077cb1075976660d61d944eb4R185 `AbstractStompSessionManager.connect()` will log then swallow exceptions raised by the abstract `doConnect()` method. However, the return value of that call is used to set the `stompSessionListenableFuture` property, which is used just after the try-catch block, triggering a `NullPointerException`.

Shouldn't the exception be logged and either re-thrown or used as the cause for a new exception that is then thrown?

**Comment by artembilan** [comment]
Thank you for catching that out!
See https://jira.spring.io/browse/INT-4075 for tracking.

**Comment by dagan** [comment]
Wow. Super awesome that you got that taken care of so quickly. Also glad you added the null check for getTaskScheduler() since that was indeed also a problem, but I assumed setting a task scheduler was simply a requirement.

**Comment by artembilan** [comment]
Glad to read such a feedback!

Eh... `TaskScheduler` isn't requirement in the `StompClientSupport`, but I decided do not overhead `StompSessionManager` with that option since it is accessible from the `stompClient`.

The problem that we didn't have test coverage before :cry: 

And more bigger problem that there is no straightforward workaround, unless target `AbstractStompSessionManager.doConnect()` overriding and providing a fake `ListenableFuture` in the `catch` block there.

Only good news that we are going to release all those fixes in the end of this week :smile: 

So, that is a time to find and share more bugs :wink: !
