### ISSUE TITLE
RedisLockRegistry timeout issues 

### ISSUE THREAD

**Issue by psgrewal** [spring-projects/spring-integration#1888]
Hi 

We discovered an issue with `RedisLockRegistry` when in a single process , we try to lock on the same lock from different threads.  For eg:

1. ThreadA locks on Lock1. It acquires lock. 
2. Lock times out on redis
3. ThreadA tries to unlock. Now at this point, the unlock method throws an "IllegalStateException", however it does not unlock the local reentrant lock
4. ThreadB when it tries to acquire the lock can never succeed because the reentrant lock is held by ThreadA.

I think in addition to throwing the exception, we should release the reentrant lock as well. However there maybe more reason not to do this ?

**Comment by artembilan** [comment]
H-m. Not sure in your concern.
The code looks like:
````java
try {
	if (this.reLock-- <= 0) {
		try {
			this.assertLockInRedisIsUnchanged();
                        ...
	    }
	}
}
finally {
	Lock localLock = RedisLockRegistry.this.localRegistry.obtain(this.lockKey);
	localLock.unlock();
}
````
Where that `assertLockInRedisIsUnchanged()` throws mentioned `IllegalStateException("Lock was released due to expiration; ")`.

As for me the final `finally` block does the work to unlock "local reentrant lock".

Would you mind to come back to us with some test-case to reproduce and play locally?

Thanks

**Comment by psgrewal** [comment]
I have pasted a sample code snippet that can replicate this issue. I believe the issue occurs at an earlier stage, because the IllegalStateException is thrown earlier in the unlock function by this block 
```
if (!Thread.currentThread().equals(this.thread)) {
				if (this.thread == null) {
					throw new IllegalStateException("Lock is not locked; " + this.toString());
				}
				throw new IllegalStateException("Lock is owned by " + this.thread.getName() + "; " + this.toString());
			}
```

Code snippet to replicate issue is below :
```
package com.abc.infra.caching;

import org.springframework.data.redis.connection.jedis.JedisConnectionFactory;
import org.springframework.integration.redis.util.RedisLockRegistry;

import redis.clients.jedis.JedisShardInfo;

public class RedisLockExample {

	public static void main(String args[]) {
		JedisConnectionFactory redisConnectionFactory = new JedisConnectionFactory(
				new JedisShardInfo("ABCDE", 6234, 300000));
		String registryKey = "TEST";
		RedisLockRegistry registry = new RedisLockRegistry(
				redisConnectionFactory, registryKey, 30000);
		RedisLocker locker = new RedisLocker(registry);
		Thread thread1 = new Thread(locker, "Thread1");
		thread1.start();
		try {
			thread1.join();
		} catch (InterruptedException e) {
			System.out.println(e.getMessage());
		}
		System.out.println("Exited thread 1");
		Thread thread2 = new Thread(locker, "Thread2");
		thread2.start();
		try {
			thread2.join();
		} catch (InterruptedException e) {
			System.out.println(e.getMessage());
		}
		System.out.println("Exited thread 2");
	}
}

class RedisLocker implements Runnable {
	private RedisLockRegistry registry;
	String lockName = "ExampleLock5";

	RedisLocker(RedisLockRegistry registry) {
		this.registry = registry;
	}

	public void run() {
		System.out.println("Obtaining lock : " + lockName + " on thread : "
				+ Thread.currentThread().getName());
		try {
			registry.obtain(lockName).lock();
			System.out.println("Obtained lock : " + lockName + " on thread : "
					+ Thread.currentThread().getName());
			try {
				Thread.sleep(40000l);
			} catch (InterruptedException e) {
				System.out.println(e.getMessage());
			}
			System.out.println("Releasing lock : " + lockName + "on thread : "
					+ Thread.currentThread().getName());
		} catch (Throwable e) {
			System.out.println("Some exception " + e.getMessage());
		} finally {
			registry.obtain(lockName).unlock();
		}
	}
}
``` 
For spring , we are using 4.3.1 and for jedis we are using 2.9.0. Let us know if you can replicate this issue or need any further information on my end

**Comment by artembilan** [comment]
Wait!

Quoting you:
> Lock times out on redis

That's why I show you that `finally` block which correctly unlock the local lock as well.

Now you are talking about the block before that.
Let's take a look at that!
```
if (!Thread.currentThread().equals(this.thread)) {
	if (this.thread == null) {
		throw new IllegalStateException("Lock is not locked; " + this);
	}
throw new IllegalStateException("Lock is owned by " + this.thread.getName() + "; " + this);
}
```
So, only the locker Thread can unlock the lock.
And one more `IllegalStateException` only if we haven't locked before.

I'll take a look to your code later, but would you mind do not use `registry.obtain(lockName)` for `unlock()`, but use local variable after the first obtain.

OTOH looks like your `finally` on the wrong place. 
The normal lock usage pattern is:
```
lock.lock();
try {
...
}
finally {
	lock.unlock();
}
```

**Comment by psgrewal** [comment]
Hi 

I agree with the usage pattern. fixed that. 

On the point of threads, whether I unlock using
```
lock.unlock()
``` 
or 
```
registry.obtainLock("key").unlock()
```
I am not switching threads. So as long as registry.obtainLock("key") returns the correct lock, it would unlock properly. 

It looks like the issue here is mostly around how we are using this library. We assumed the name "registry" meant that you would not only create the locks but also act as the storage for locks. I would recommend adding some documentation to the obtainLock or an example snippet of code on how to use this class

Further , given that we are using redis, it would have been "maybe" a little more easier if the registry implements Lock and handled locking and unlocking for us but that maybe a larger argument :-)

Thank you for your help on this, highly appreciated!

**Comment by psgrewal** [comment]
Closing issue as once suggested changes are made, the component works as expected

**Comment by artembilan** [comment]
You know, I'm going to agree with you. We have a problem there.
See https://jira.spring.io/browse/INT-4105

**Comment by jimpouwels** [comment]
Hello,

We're facing a similar issue in spring-integration-redis 4.3.17.

Our application is multi-threaded, and multiple threads will try to lock certain userIds. Whenever a thread locks a user, but for some reason fails to release the lock (e.g. Redis connection issue) we run into the issue that we can never acquire a lock for that userId anymore, even after the that lock expires in Redis.

When debugging, I see that the lock in redis is not found (due to expiration)
`RedisLockRegistry.RedisLock lock = this.findLock((Collection)this.hardThreadLocks.get(), lockKey);
        if (lock != null && lock.thread != null) {`

So the following code returns a new lock 
`if (lock == null) {
            lock = this.findLock((Collection)this.weakThreadLocks.get(), lockKey);
            if (lock == null) {
                lock = new RedisLockRegistry.RedisLock((String)lockKey);
                if (this.useWeakReferences) {
                    this.getWeakThreadLocks().add(lock);
                }
            }
        }`

But when trying to acquire this new lock, that fails. It's important to mention that the thread that tries to acquire the new lock for that userId, is not the same thread as the thread that locked the userId to begin with but wasn't able to release (unlock) it.

Any guidance on how to work with this?

Kind regards,
 Jim Pouwels

**Comment by garyrussell** [comment]
Please don't comment on 2+ year old issues; open a new issue for a legitimate bug.

**Comment by jimpouwels** [comment]
@garyrussell  https://github.com/spring-projects/spring-integration/issues/2660
