### ISSUE TITLE
Make IntegrationComponentScanRegistrar easier to subclass

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-integration#2007]
https://github.com/spring-projects/spring-boot/pull/7718 adds automatic `@IntegrationComponentScan` support to Spring Boot, however, the `AutoIntegrationComponentScanRegistrar` class is a little messy since it mocks out `StandardAnnotationMetadata`. If `IntegrationComponentScanRegistrar` were refactored a little things could be a lot cleaner.

Specifically the top lines `registerBeanDefinitions` could be extracted into a protected `getBasePackages(AnnotationMetadata importingClassMetadata, BeanDefinitionRegistry registry)` method which we could simply override and return the result of `AutoConfigurationPackages.get(beanFactory)`.

**Comment by artembilan** [comment]
Yes, we can do that in SI, but then we have to release one more `4.3.x` somewhere close to Boot `1.5` release. 
I think the current solution is pretty safe and can be fixed eventually.
The main reason of the fix to overcome annoying issue always forgetting to add `@IntegrationComponentScan` alongside with the `@SpringBootApplication`, when we deal with `@MesaagingGateway`s.
Otherwise, If you're fine to stay with SI BUILD-SNAPSHOT, I'll provide an appropriate fix tomorrow.
Definitely`IntegrationComponentScanRegistrar` wasn't designed for extension. It is just for `@Import` on particular annotation 😀

**Comment by philwebb** [comment]
+1 I'm merging the other one anyway. Just I think we could improving things in Boot 2.0.

**Comment by philwebb** [comment]
What milestone did this make it into?

**Comment by artembilan** [comment]
`5.0 M2` - just a day before Spring Boot 1.5 RC1 😄 : http://spring-calendar.cfapps.io

**Comment by philwebb** [comment]
How come you don't use the `milestone` feature of GitHub?

**Comment by artembilan** [comment]
Because our main tracked is still JIRA: https://jira.spring.io/browse/INT

**Comment by philwebb** [comment]
Oh, that's confusing!

**Comment by garyrussell** [comment]
@philwebb We can backport to 4.3.x if you'd like to get it into a boot 1.5 release.

**Comment by philwebb** [comment]
@garyrussell There's no big hurry, we've got something that works.
