### ISSUE TITLE
Update to Smack 4.1.9 or newer

### ISSUE THREAD

**Issue by daniloguimaraes** [spring-projects/spring-integration#2071]
Hey guys,

How are you?

Ignite realtime had announced that [Smack 4.1.9 solves a critical security vulnerability](https://community.igniterealtime.org/blogs/ignite/2016/11/22/smack-security-advisory-2016-11-22).

Nowadays, Spring Integration is using Smack 4.1.7 (both 4.3.x and 5.x versions).

I lookup JIRA and found [an issue about updating to 4.1.5](https://jira.spring.io/browse/INT-3834?jql=project%20%3D%20%22INT%22%20AND%20text%20~%20%22smack%22), but it is already closed by @artembilan .

**My question: is there any plan to update the dependency version?**

Thank you very much.

**Comment by artembilan** [comment]
Always welcome @daniloguimaraes !

Feel free to provide contribution: https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.adoc

**Comment by artembilan** [comment]
@garyrussell ,

WDYT if we upgrade already to the Smack 4.2.0 :http://www.igniterealtime.org/projects/smack/index.jsp ?

/CC @Flowdalic

**Comment by garyrussell** [comment]
OK w/ me, but check with @wilkinsona too.

**Comment by artembilan** [comment]
That's true.

And there is also @gregturn with some XMPP support in Spring WS 😄 

At least, in forehead, we (Spring Integration) are not compatible with their latest version, but at the same time it is fine to have such a breaking change in our current major version.

**Comment by Flowdalic** [comment]
> WDYT if we upgrade already to the Smack 4.2.0 :http://www.igniterealtime.org/projects/smack/index.jsp ?

I'm always happy if users switch to the newest stable version. But it's also fine if you go with 4.1.9, which is battle tested, and wait with 4.2 until your next major release.

**Comment by wilkinsona** [comment]
The Platform's already on 4.1.9 in Athens, Brussels, and Cairo. I am firmly in favour of moving to 4.2.x in Cairo (so SI 5). The more up-to-date everyone's dependencies are the better.

**Comment by artembilan** [comment]
Thank you, @wilkinsona , for sharing your vision.

Nevertheless, one more time: AFAIK, Spring WS also has support for XMPP and its current version is `2.4.1.BUILD-SNAPSHOT`. I'm pretty sure this version is used from the IO Brussels as well and since Smack `4.2.x` looks breaking (at least for SI), it doesn't go for us to upgrade Spring WS silently and be compatible with the IO Brussels. Unless Spring WS `3.0` based on SF `5.0` for IO Cairo 😄 
(Or at least `2.5` to let users know that it based on fresh dependencies)

//CC @gregturn , @poutsma

**Comment by Flowdalic** [comment]
> and since Smack 4.2.x looks breaking

It is. Only patch level Smack releases are non API breaking (e.g. 4.1.9 is a drop in replacement for all 4.1.X releases).

**Comment by wilkinsona** [comment]
I don't want Spring Web Services to prevent a new major version of Spring Integration from keeping its dependencies up-to-date. If that requires a new version of Spring Web Services in the Spring Framework 5.0/Spring Boot 2.0/Spring IO Platform Cairo timeframe then that's what I would like to happen.

**Comment by gregturn** [comment]
I just pushed a change bumping Spring WS to Smack 4.1.9. I'm now investigation moving to 4.2.0, and if that's easy/hard.

**Comment by artembilan** [comment]
@gregturn ,

Thank you very much for looking into that!

What I know from the Spring Integration perspective Smack `4.2.0` isn't compatible with `4.1.x`.
That is fine for us to upgrade that way because we are in major `5.0` version.
The problem with Spring WS that there is no new major version branch and according to the `Brussels` IO Platform compatibility you can't upgrade to such a breaking Smack version.

See @wilkinsona 's comment above:
>  If that requires a new version of Spring Web Services in the Spring Framework 5.0/Spring Boot 2.0/Spring IO Platform Cairo timeframe then that's what I would like to happen.

Let us know if that is really your plan.

**Comment by gregturn** [comment]
Spring WS's plan would be to have a 3.0 version that rebases against Spring 5 + Java 8 (which is not, by the way, currently planned).

We have made other alterations, like upgrading from Wss4j 2.0 -> 2.1 with a minor release in Spring WS. So it's arguable that we could do a new minor release for Spring WS for a minor release of Smack. I don't know how easy/hard the new API is. If you could provide a link where you changed the API in SI, that would be handy for me to read.

**Comment by artembilan** [comment]
Well, if that is Spring WS `2.5` with the Smack `4.2`, then it will work for us.
@wilkinsona , your opinion?

No, I haven't tried yet to move SI to Smack `4.2`. I need to know if we go that first of all.

Thank you!

**Comment by wilkinsona** [comment]
That sounds good to me in the IO Platform Cairo, Boot 2.0, Spring Framework 5.0 timeframe
