### ISSUE TITLE
`logInputChannel` should be `logChannel`?

### ISSUE THREAD

**Issue by robmoore** [spring-projects/spring-integration#2100]
Looking at the documentation for [logging adapter](https://github.com/spring-projects/spring-integration/blob/master/src/reference/asciidoc/logging-adapter.adoc) at the example at the end of the document. Should `logInputChannel` be `logChannel` instead?

```
  @Bean
    public MessageChannel logInputChannel() {
        return new DirectChannel();
    }
```

**Comment by artembilan** [comment]
That's true.
Should be fixed.
Although I think we can remove that `logInputChannel()` bean definition altogether, since `@ServiceActivator` populates one by default.
And `@MessagingGateway` will reuse that auto-created `MessageChannel`.

Thank you for the report and feel free with [Contribution](https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.adoc)!

**Comment by robmoore** [comment]
I've submitted a [pull request] (https://github.com/spring-projects/spring-integration/pull/2101)
