### ISSUE TITLE
Setting external Scanner fails the Assert in FileReadingMessageSource

### ISSUE THREAD

**Issue by deepeshgarg** [spring-projects/spring-integration#2127]
Following code in `FileReadingMessageSource` may need correction (line 339 - 347)
````java
	Assert.state(!(this.scannerExplicitlySet && (this.filter != null || this.locker != null)),
				"The 'filter' and 'locker' options must be present on the provided external 'scanner': "
						+ this.scanner);
		if (this.filter != null) {
			this.scanner.setFilter(this.filter);
		}
		if (this.locker != null) {
			this.scanner.setLocker(this.locker);
		}
````

The condition in `Assert` looks to check for filter and locker in `this` but the message implies that properties are expected to be set on scanner. 
When `scannerExplicitlySet` is `true` It seems that the `Assert` would pass when both `this.filter` and `this.locker` Is `Null` while based on the message it seems the `Assert` should pass when both `scanner.getFilter()` and `scanner.getLocker()` is `Not Null`.
Also code after assert doesn't take `scannerExplicitlySet` into consideration and always sets the `filter` and `locker` on `scanner`.

**Comment by artembilan** [comment]
The purpose of that assert is like: 

when you provide external `scanner` you can set `filter` or `locker` directly on the `FileReadingMessageSource` you should move them to that scanner.

You might miss the negate (`!`) operator in the beginning of the assert.
We pass that assert when `this.scannerExplicitlySet == false` or we don't nor `filter`, neither `locker`.

The code after that assert doesn't need to consult `scannerExplicitlySet`, because if we there already either we don't have `filter` or `scanner` is internal instance.

I've just done the simple test-case:
```
FileReadingMessageSource fileReadingMessageSource = new FileReadingMessageSource();
fileReadingMessageSource.setDirectory(new File("tmp"));
fileReadingMessageSource.setLocker(mock(FileLocker.class));
fileReadingMessageSource.setScanner(mock(DirectoryScanner.class));
fileReadingMessageSource.afterPropertiesSet();
```
And the output is exactly what is implied with that assert:
```
java.lang.IllegalStateException: The 'filter' and 'locker' options must be present on the provided external 'scanner': Mock for DirectoryScanner, hashCode: 1770070706

	at org.springframework.util.Assert.state(Assert.java:71)
	at org.springframework.integration.file.FileReadingMessageSource.onInit(FileReadingMessageSource.java:339)
```

What am I missing?
Thanks

**Comment by deepeshgarg** [comment]
Thanks for the reply. I guess you are right.

I am using schema based configuration and realised that although the locker and filter are not explicitly set on the file:inbound-channel-adapter, setting attribute prevent-duplicate will create a AcceptOnceFileListFilter for it. Since a custom DirectoryScanner is also set, the Assert is failing, which is expected.

Note to self: Read documentation more closely.

Regards
