### ISSUE TITLE
Using the example shown in Spring Batch Integration "13.1.3 Providing Feedback with Informational Messages" does not work

### ISSUE THREAD

**Issue by lgoldstein** [spring-projects/spring-integration#2161]
When attempting to define a `StepExecutionListener` as shown in the [documentation](http://docs.spring.io/spring-batch/trunk/reference/html/springBatchIntegration.html#providing-feedback-with-informational-messages), the batch execution simply hangs forever. Some debugging yielded the following problem - when `StepExecutionListener#afterStep` is invoked, the code will (eventually) send the `StepExecution` to the default request channel and then creates a *temporary* reply channel and waits for an `ExitStatus` response - which will *never* arrive since the logging adapter does not know it should generate a response (and is unable to generate one since it is not _Spring Batch_-aware). I therefore believe the example is somehow incomplete and should be modified and documented to work properly.

**Comment by lgoldstein** [comment]
The "fix" is simple - in the (derived) `LoggingHandler` add the following code:

```java
    @Override
    protected void handleMessageInternal(Message<?> message) throws Exception {
        MessageHeaders headers = message.getHeaders();
        StepExecution stepExecution = (StepExecution) message.getPayload();
        logger.info("handleMessageInternal(headers=" + headers + "): " + stepExecution);

        Object replyChannel = headers.get(MessageHeaders.REPLY_CHANNEL);
        if (replyChannel == null) {
            return; // for beforeStep there is no reply
        }

        Validate.isInstanceOf(MessageChannel.class, replyChannel, "Invalid reply channel type: %s", replyChannel);
        ExitStatus exitStatus = stepExecution.getExitStatus();
        logger.info("handleMessageInternal(headers=" + headers + ") reply=" + exitStatus);
        ((MessageChannel) replyChannel).send(new GenericMessage<>(exitStatus));
    }
```

**Comment by artembilan** [comment]
First of of all this question more belongs to [Spring Batch](https://jira.spring.io/browse/BATCH) project.

The sample is there is shown for the `beforeStep()`, which is `void`. Therefore `<int:logging-channel-adapter>` is the best choice to finish the flow. 

The `afterStep()` is indeed a *request/reply* and in that case some `AbstractMessageProducingHandler` should be used to emit reply back to the gateway. For example the `<service-activator>` for some POJO method invocation.

If you take a look closely to the image in that Spring Batch documentation, you'll see that there is a `router`.
I'd say that its decision is based on the `StepExecutionListener` method. In that case the `beforeStep()` message is sent to the e-mail Outbound Channel Adapter. And the `afterStep()` to some `<transformer>` to build the proper `ExitStatus` for the reply to that `<gateway>` for the `afterStep()` method.

I agree that the sample is not so clear, but it just represents the general idea how to talk from Spring Batch to Spring Integration and back. All other, more comprehensive info, is already out of Spring Batch scope and you really should go to Spring Integration for answers for your use-case in that flow.

See more in the [Messaging Gateway](http://docs.spring.io/spring-integration/reference/html/messaging-endpoints-chapter.html#gateway).

(Closing this one since there is nothing to do from Spring Integration perspective to that Spring Batch sample)
