### ISSUE TITLE
RedisInboundChannelAdapter "drops" channel ID

### ISSUE THREAD

**Issue by matthjes** [spring-projects/spring-integration#2268]
Hi,

The current implementation of the `RedisInboundChannelAdapter` does not add the channel ID to the header when a message is received. This makes it impossible to filter / route messages based on the topic / channel ID. Though I can subscribe to multiple topics, I do not get any information about which message belongs to which topic.

I have a small fix for this (see below). You only have to change the `handleMessage()` method of the MessageListenerDelegate to accept the channel ID as a parameter and then also change the `convertMessage` appropriately. Note that the default `MessageConverter` is a `SimpleMessageConverter`, which also ignores the header, so you have to use a custom `MessageConverter`.

```java
public class RedisInboundChannelAdapter extends MessageProducerSupport {
    ...
    private Message<?> convertMessage(Object object, String channel) {
        Map<String, Object> headers = new HashMap<>();
        headers.put("topic", channel);
        return this.messageConverter.toMessage(object, new MessageHeaders(headers));
    }

    private class MessageListenerDelegate {

	@SuppressWarnings("unused")
	public void handleMessage(Object object, String channel) {
		sendMessage(convertMessage(object, channel));
    }
}
```

I'll submit a PR when I find the time to fix this.

**Comment by artembilan** [comment]
The project is called **Spring**.

Please, be careful if you would like to get a help from us.

**Comment by matthjes** [comment]
Hm, ok, I‘m deeply deeply sorry for the typo...

**Comment by artembilan** [comment]
I think your request is valid.
Please, go ahead with the PR on the matter.

Consider to add `SOURCE` constant to the `RedisHeaders`.
It must be source because of: https://github.com/spring-projects/spring-data-redis/blob/master/src/main/java/org/springframework/data/redis/listener/RedisMessageListenerContainer.java#L967

Also we should wrap into the `if (source != null)` and don't create those extra headers object for nothing.

Thank you for considering contribution and proposing an improvement!
