### ISSUE TITLE
check for both Spring MVC and for Spring WebFlux when deciding to register the Integration Graph controller

### ISSUE THREAD

**Issue by joshlong** [spring-projects/spring-integration#2358]
`IntegrationGraphControllerRegistrarImportSelector` checks for the `DispatcherServlet`, which fails in a Spring WebFlux application. I copied and pasted the relevant code to a separate class hiearchy, commented out the test for Spring MVC and then ran it in a Spring WebFlux app, and it seems to work.

**Comment by garyrussell** [comment]
Contributions are welcome 😄

**Comment by artembilan** [comment]
In the WebFlux module we use the code like:
```
	/**
	 * The {@code boolean} flag to indicate if the
	 * {@code org.springframework.web.reactive.result.method.RequestMappingInfo}
	 * is present in the CLASSPATH to allow to register the Integration server reactive components.
	 */
	public static final boolean WEB_FLUX_PRESENT =
			ClassUtils.isPresent("org.springframework.web.reactive.result.method.RequestMappingInfo",
					WebFluxContextUtils.class.getClassLoader());

```
to indicate that we are good to go with the WebFlux server components registration.

I don't think that we need to do one class in this `webflux` module. 
I think as the fix there should be enough to add similar condition to the `IntegrationGraphControllerRegistrarImportSelector`:
```
if (HttpContextUtils.WEB_MVC_PRESENT || WEB_FLUX_PRESENT) {
	return new String[] { IntegrationGraphControllerRegistrar.class.getName() };
}
```

The JavaDocs of the `@EnableIntegrationGraphController` should be improved respectively. 

That will work properly just because `spring-integration-http` is direct dependency of of the `spring-integration-webflux`.
