### ISSUE TITLE
ServiceActivator should support a pattern for referencing channels

### ISSUE THREAD

**Issue by ngbalk** [spring-projects/spring-integration#2505]
https://github.com/spring-projects/spring-integration/blob/de9f8d7ccd2adbb3e3b5b44d32e7eccfaa8ea72e/spring-integration-core/src/main/java/org/springframework/integration/annotation/ServiceActivator.java#L56

When creating MessageRouters and referencing a channel to apply to, we should support matching channels based on patterns so that MessageRouters can be shared across different channels, especially when the channels aren't known ahead of time (in which case you could match on '*')

For an example, I'm looking at:
https://github.com/spring-cloud-stream-app-starters/router/blob/c888df571fbda3f529d712a0f520bda24c09f794/spring-cloud-starter-stream-sink-router/src/main/java/org/springframework/cloud/stream/app/router/sink/RouterSinkConfiguration.java#L51

and thinking that it could be very useful to share that MessageRouter across multiple channels.

It may look something like:

```java
@ServiceActivator(inputChannel = "*")
```

**Comment by artembilan** [comment]
Related issue: https://github.com/spring-cloud-stream-app-starters/router/issues/2

It is not possible and not going to happen.
The reason is like this: there are many different `MessageChannel` implementations. The `@ServiceActivator` is a top-level abstraction behind a `ConsumerEndpointFactoryBean` with hard logic to determine a target endpoint type and many other options for the `ServiceActivatingHandler` in the end. That's is really from a `MessageChannel` level dictation to stick with only a single input for the endpoint.

I understand your frustration because all your input channels might be just as the same time and with the same option requirements, but that's not what is going to be possible with Spring Integration, where a `MessageChannel` is one of first class citizens and we really have to count with its abstraction and way to use.

There is a solution for you to come up with such a fan-in scenario. You need to configure those channels like this:
````java
		@Bean
		@BridgeTo(Sink.INPUT)
		public MessageChannel channel1() {
			return new DirectChannel();
		}
		
		@Bean
		@BridgeTo(Sink.INPUT)
		public MessageChannel channel2() {
			return new DirectChannel();
		}

		@Bean
		@BridgeTo(Sink.INPUT)
		public MessageChannel channel3() {
			return new DirectChannel();
		}
````

There is another option called [`WireTap`](https://docs.spring.io/spring-integration/docs/5.0.6.RELEASE/reference/html/messaging-channels-section.html#channel-wiretap), but it needs some endpoints to subscriber to all those channels anyway...

**Comment by ngbalk** [comment]
Thanks for the response.  I'll take a look at this solution.
