### ISSUE TITLE
DirectChannel should specify whether this is an Input or Output

### ISSUE THREAD

**Issue by ngbalk** [spring-projects/spring-integration#2525]
I've noticed that when I'm using Spring Cloud Streams (take the Sink.class and Source.class for example), both MessageChannels "output" and "input" are created as DirectChannels.

```java
public interface Sink {

	String INPUT = "input";

	@Input(Sink.INPUT)
	SubscribableChannel input();

}
```
```java
public interface Source {

	String OUTPUT = "output";

	@Output(Source.OUTPUT)
	MessageChannel output();

}
```

I actually have no way of knowing whether this DirectChannel is an output or an input (besides looking at the bean name, but I wouldn't want to rely on that).

It would be helpful for me, especially when using a `@GlobalChannelInterceptor`, to know whether a MessageChannel is an input or output (i.e. annotated with `@Input` or `@Output`).  That way, in a `ChannelInterceptor.preSend()` I could do some checking of whether this is an inbound message or an outbound message and apply logic accordingly.

Curious to hear what people think / maybe I'm missing something obvious.

NOTE: I raised this on DirectChannel because I see that it applies to both inbound and outbound channels, and other channels are more specific to either inbound or outbound.  However perhaps this makes sense in another class too...

Thanks
Nick

**Comment by garyrussell** [comment]
This belongs in `spring-cloud-stream`, not here. Spring Integration itself knows nothing about how applications are using channels; perhaps spring-cloud-stream could provide some registry or similar where you can lookup a channel to see what type it is.

**Comment by artembilan** [comment]
That's not Spring Integration question. Please, consider to move it into Spring Cloud Stream.
As far as we know Spring Integration provides a lot of `MessageChannel` implementations to build integration flows any complexity and for any possible task.
It is just not restricted with the `DirectChannel` and there is fully no any opinion about some particular built-in beans, like it is in the Spring Cloud Stream.
Also you should keep in mind that Spring Cloud Stream may have may inputs, as well as many outputs, so that might be really your one responsibility to sever one type into one channel interceptor and other to another, respectively, but definitely do that yourself because after channel creation there is no knowledge about the binding interface anymore...

Anyway Spring Integration can't help here because the binding and auto-configuration is already out of scope of this project.

Thanks for understanding.

Closing as `Invalid`

**Comment by ngbalk** [comment]
Apologies, I'll open this in spring-cloud-streams.  Thanks Gary!
