### ISSUE TITLE
Fix InboundChannelAdapter's javadoc

### ISSUE THREAD

**Issue by manueljordan** [spring-projects/spring-integration#2559]
Hello, the annotation [InboundChannelAdapter](https://github.com/spring-projects/spring-integration/blob/master/spring-integration-core/src/main/java/org/springframework/integration/annotation/InboundChannelAdapter.java) has currently the following:

```
	/*
	 {@code SmartLifecycle} options.
	 Can be specified as 'property placeholder', e.g. {@code ${foo.autoStartup}}.
	 */
	String autoStartup() default "true";
```

* I want fix it, but since there is no a `JIRA` issue for this, May I fix it without create one for this?
* Should create a new branch to fix it? or I can fix it directly in master? If not, how? it because there is no a `INT-###` pattern.

Thank you

**Comment by artembilan** [comment]
Hello, @manueljordan !

Thank you for the report, although it's not clear what is the problem.
Please, elaborate: maybe there is just nothing to fix after discussion with us 😉 

Since you have already raised this GitHub issue, it is fully enough: from the bug tracking perspective it is equal to have a JIRA ticket.
You definitely have to create a new branch against the latest `master` and call let's say `GH-2559`.
In the commit message you need to mention this issue with an appropriate [special keyword](https://help.github.com/articles/closing-issues-using-keywords/).

I agree that we need to fix that Contribution doc to reflect the procedure against GitHub issues, but that's different story. 

Hope this helps

**Comment by manueljordan** [comment]
Thanks for the clarification Artem!

Yes, now is clear. Remember I used to work normally through `JIRA`.
So I was not sure how send a PR and refer a non jira ticket 

>Please, elaborate: maybe there is just nothing to fix after discussion with us

![screen shot 2018-09-06 at 11 09 38 am](https://user-images.githubusercontent.com/2552795/45170442-856d3300-b1c5-11e8-9edc-a7b2c9d95bc3.png)

`Javadoc` normally starts with `/**` and is marked all the text with blue (it for IDE based on Eclipse). But according with the figure, the `autoStartup()` attribute/method is wrong, it just is `/*`

**Comment by manueljordan** [comment]
>Obvious fix for beginning contributors!

Well .... We always have a beginning

>Plus will back-port to the previous support version.

Not sure if that means if I should do that. If yes, give me instructions to accomplish that.
(URL for a tutorial would be valuable)
I am assuming it is to reflect this fix from 5.0.x to SI previous releases such as: 3.0.x, 4.0.x etc .. 

Even when your IDE did not help that, I had assume that the `Gradle` task for `javadoc` should had arised an error about that. Normally I have a job in jenkins about javadoc for main and test

I want contribute to this project, I know I am rusty in some points. But ready to learn

**Comment by artembilan** [comment]
No, you don't need to do anything about back-porting.
That's already a *Committer* responsibility.

The current version is `5.1`. I think only about back-porting to the `5.0.x`.
The `3.0.x` is in EOL (End Of Life) for a while.
We can consider to back-port to `4.3.x`, but having this as only a cosmetic non-bug fix this won't have too much value to contribute it back to the version which is moving to its EOL as well.

Yes, we have `javadoc` task in our Gradle graph, but it doesn't look like it catches that since you see that this issue exists for a while already.
I'd be glad if you can share your experience on the matter as a contribution as well: who know how many else Javadocs we have as a plain comments 😉

**Comment by manueljordan** [comment]
Thanks @artembilan 

> That's already a Committer responsibility.

Ok, just for your consideration, if is possible do that from my side, I could do it. Just I need indications/instructions.

>Yes, we have javadoc task in our Gradle graph, but it doesn't look like it catches that since you see that this issue exists for a while already.

Very hard to be detected even with Eclipse, because it is considered a multi line comment.

>I'd be glad if you can share your experience on the matter as a contribution as well: who know how many else Javadocs we have as a plain comments

If you mean how I have detected this typo error? I was doing a tech review for a book and I arrived to that annotation and at a first glance I saw green text and not the blue how was expected

Be sure if I detect more cases about this kind I will fix it. Don't worry
