### ISSUE TITLE
RouterSpec channelMapping takes no MessageChannel.

### ISSUE THREAD

**Issue by dschulten** [spring-projects/spring-integration#2754]
**Affects Version(s):**  5.1.3

## Enhancement

AbstractRouterSpec.defaultOutputChannel takes both a channelName and a MessageChannel.
However, RouterSpec.channelMapping only takes a channelName, but not a MessageChannel.

When using the DSL, I try to avoid explicit channel names and prefer the `IntegrationFlow.getInputChannel()` method to look up the input channel for a flow.

Currently I must use "mySubflow.input" for the `channelMapping` but I can use defaultOutputChannel(mySubFlow().getInputChannel()) for the default.

**Comment by artembilan** [comment]
The current implementation fully honors a target `AbstractMappingMessageRouter` contract which is only based on the channel names:
```
void setChannelMapping(String key, String channelName);
...
void setChannelMappings(Map<String, String> channelMappings);
```

We can improve the `RouterSpec` to accept a `MessageChannel` as well, but you need to ensure that your channel is a `NamedComponent` over there. Since the target `AbstractMappingMessageRouter` expects from us only channel names.

As a workaround your can do something like this:
```
m -> m.channelMapping(true, ((NamedComponent) myFlow.getInputChannel()).getComponentName())
```

Feel free to raise a Pull Request with such an improvement.
We would need to check for `NamedComponent` in a new `channelMapping()` method before calling a delegate.
