### ISSUE TITLE
Refactoring breaks bean initialization

### ISSUE THREAD

**Issue by bechte** [spring-projects/spring-integration#2767]
**Affects Version(s):** 5.1.0 (and higher), still correct in 5.0-branch.

---

## Bug report

The method `org.springframework.integration.file.remote.synchronizer.AbstractInboundFileSynchronizingMessageSource#onInit()` was refactored on Jul 25, 2018, commit: 0d0605be783a2648d725e87e365295614c36616d

Unfortunately, this changes breaks the `SmbInboundFileSynchronizingMessageSource` of the `spring-integration-smb` project, version: `1.0.0.RELEASE`. I wonder if this was done intentionally or by accident. The `@Override` does not seem to make sense, at least I couldn't find an `onInit()` method in the class hierarchy that could be overwritten at this point.

Previously, it was using `afterPropertiesSet()` which is defined and annotated correctly in the `AbstractExpressionEvaluator` class.

Can you try to find out whether this change is a bug or not and whether I should report an issue with the SMB extension or provide a PR for you guys?

Thanks in advance.

Bechte

**Comment by garyrussell** [comment]
It was intentional; the SMB extension currently does not have a version that is compatible with Spring Integration 5.1; the master is still at 5.0.4.

Please open an [issue here](https://github.com/spring-projects/spring-integration-extensions/issues) to request a version that is compatible with 5.1.
