### ISSUE TITLE
Not able to set custom converters to MongoDbMessageStore

### ISSUE THREAD

**Issue by debesay** [spring-projects/spring-integration#2936]
**Affects Version(s):** \<Spring Integration version>
      <artifactId>spring-integration-mongodb</artifactId>
      <version>5.1.2.RELEASE</version>
---

As explained in https://stackoverflow.com/questions/56215529/configurablemongodbmessagestore-failed-to-instantiate-org-springframework-messa#
there is a need to be able to add custom converters to MongoDbMessageStore or successfully inject ConfigurableMongoDbMessageStore with a MongDbTemplate containing custom converters. 
Please assist.

**Comment by artembilan** [comment]
Well, that is really why we have introduced a `ConfigurableMongoDbMessageStore`: the way when you can inject your own `MongoTemplate` with any possible external configuration.

We can't abuse internally a provided instance because that one can be used in any other place.
So, if you provide a  `MongoTemplate` we don't mutate it internally. Here is a logic:
```
if (this.mongoTemplate == null) {
			if (this.mappingMongoConverter == null) {
				this.mappingMongoConverter = new MappingMongoConverter(new DefaultDbRefResolver(this.mongoDbFactory),
						new MongoMappingContext());
				this.mappingMongoConverter.setApplicationContext(this.applicationContext);
				List<Object> customConverters = new ArrayList<>();
				customConverters.add(new MessageToBinaryConverter());
				customConverters.add(new BinaryToMessageConverter());
				this.mappingMongoConverter.setCustomConversions(new MongoCustomConversions(customConverters));
				this.mappingMongoConverter.afterPropertiesSet();
			}
			this.mongoTemplate = new MongoTemplate(this.mongoDbFactory, this.mappingMongoConverter);
		}
```

So, you should consider to add those `MessageToBinaryConverter` and `BinaryToMessageConverter` into your external `MongoTemplate` instance.

The `MongoDbMessageStore` is so tied to the messaging that its internal  `MongoTemplate`, together with those internal converters, is fully not feasible for any other scenarios.

But as Gary said in the mentioned SO question, there is no reason to worry about a `ConfigurableMongoDbMessageStore`: just enough to provide a `MongoDbFactory` and the first one will take care about the proper configuration for an internal `MongoTemplate`!

**Comment by garyrussell** [comment]
@artembilan But can't we add a hook to allow him to add his custom converter to the template? From the SO comments..

> I tried the MongoDbMessageStore first but it could not decode/encode a field property in my pojo of type java.time.ZonedDateTime. I have added a custom converter for this to the MongoTemplate, which I am able to use with my MongoRepository dao with no problem. But I have not found a way to use these custom converters with the MongoDbMessageStore, hence trying out the ConfigurableMongoDbMessageStore

Seems like `addCustomConverters()` should be possible. No?

**Comment by artembilan** [comment]
Yes, that we can do: add `setCustomConverters(Object... converters)` into the `MongoDbMessageStore`, but I'm against similar approach for the `ConfigurableMongoDbMessageStore`, since we can't mutate injected `MongoTemplate`

**Comment by garyrussell** [comment]
Agreed.
