### ISSUE TITLE
Refactor FileTransferringMessageHandler impls and resepctive Java DSL components

### ISSUE THREAD

**Issue by artembilan** [spring-projects/spring-integration#3092]
The `FileTransferringMessageHandler` hierarchy possible refactoring:
1. Pursue a consistency: an `SftpMessageHandler` always comes only with the `SftpRemoteFileTemplate`, so it looks like an `FtpMessageHandler` has to require only its `FtpRemoteFileTemplate`. Therefore `FtpMessageHandler(RemoteFileTemplate<FTPFile> remoteFileTemplate, FileExistsMode mode)` is *deprecated* and must be replaced with the `FtpRemoteFileTemplate`-based one.
2. Since `SftpMessageHandler` cannot be created from the basic `RemoteFileTemplate`, its `SftpMessageHandlerSpec` must require a proper `SftpRemoteFileTemplate`. Therefore those ctors must be *deprecated* in favor of newly introduced for `SftpRemoteFileTemplate`
3. Do same for the `FtpMessageHandlerSpec`
4. I think existing ctors in the `FileTransferringMessageHandlerSpec`, and therefore - `FileTransferringMessageHandler` should exist for a while. There might be some use-cases when we can fully rely on the generic `RemoteFileTemplate`.

**Comment by joaquinjsb** [comment]
I'm going to give a look to this as well!

**Comment by artembilan** [comment]
Kinda breaking change in the binary. Moving to the next release.

**Comment by deepak5127** [comment]
Hi artembilan ,

I am newbie to GitHub contributions. Please let me know if I can take a look into this issue. Thanks

**Comment by artembilan** [comment]
Hi @deepak5127 ,

Yes, you definitely welcome to take a look into this.
Please, make yourself familiar with our contribution process first of all: https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.adoc

Feel free to ask more question here if any.

Thank you for consider to fix it!

**Comment by deepak5127** [comment]
Sure, thanks @artembilan

**Comment by artembilan** [comment]
@deepak5127 ,

That's correct. I'm fully agree that we need to follow that change anyway.

**Comment by deepak5127** [comment]
Thanks @artembilan  . I have completed the code changes in my local branch.

Couple of questions,
1. In FtpMessageHandlerSpec, for FtpMessageHandlerSpec(FtpRemoteFileTemplate ftpRemoteFileTemplate) method, it is internally FtpMessageHandler(SessionFactory<FTPFile> sessionFactory) . This again creates new FtpRemoteFileTemplate. I think instead of calling  FtpMessageHandler(SessionFactory<FTPFile> sessionFactory), we can call FtpMessageHandler(FtpRemoteFileTemplate ftpRemoteFileTemplate, FileExistsMode mode) by sending default FtpRemoteFileTemplate.ExistsMode.NLST ? 
2. I dont see Junit written for these outbound adapters in SFTP and FTP tests. Should i write new Test cases in FtpTests and SftpTests ?

**Comment by artembilan** [comment]
Your observation is correct:
1. We definitely pursue a goal to avoid that `FtpRemoteFileTemplate` recreation.
2. Yes, more test coverage would be beneficial

Thanks; looking forward for Pull Request from you!

**Comment by deepak5127** [comment]
@artembilan Created PR
