### ISSUE TITLE
Consider Adding Selector to Gateway.

### ISSUE THREAD

**Issue by sirimamilla** [spring-projects/spring-integration#3156]
**Affects Version(s):** \5.2.x
---

## Enhancement

Adding Selecter to GatewaySpec will be great help in designing very readable integration flows.

In the First example we add the filter and then merge the response from gateway and the main channel after gateway using discard channel on filter. 

In the second example below, the flow can be very intuitive.

If we can agree that this is a good option to have, I can raise a pull request with the solution.

Example with filter option:

        @Bean
        public IntegrationFlow selectingGateway(){
            MessageChannel aggregateChannel =  = new DirectChannel();
            return f -> f
                    .channel(c->c.executor(Executors.newWorkStealingPool()))
                    .filter(m -> ((String)m).contains("bak"), e -> e.discardChannel(aggregateChannel))
                    .gateway(sf -> sf.transform(this::transformMessage))
                    .channel(aggregateChannel)
                    .log("Do Some more logic Here")
                    .bridge();
        }

Example flow with selector on Gateway:

        @Bean
        public IntegrationFlow selectingGateway(){
            return f -> f
                    .gateway(<<Selecter here>>,sf -> sf.transform(this::transformMessage))
                    .log("Do Something Here")
                    .bridge();
        }

**Comment by artembilan** [comment]
>  .gateway(<<Selecter here>>,sf -> sf.transform(this::transformMessage))

It is really not intuitive. This is a mix of concerns. You bring `filter` functionality into a gateway. More over it feels like you'll come up eventually with selector for every single EIP operator, which is not what we would like to do.
One of the main concepts in EIP and here in Spring Integration is "loosely coupling". You take blocks from the box and build your own Lego knowing that each of those blocks has their own strict purpose.
To be honest we even have staid away from Scatter-Gather implementation for a long time just because it can be implemented with other existing simpler components.

So, here is my 👎 for this request.

Thanks for understanding.

**Comment by artembilan** [comment]
I think we are not going to add this into the framework. 
You are free to go with any custom solutions in your project.
Therefore I'm closing this in favor of the mentioned issue #3155 for extensions.

Let's continue discussion over there and in the linked PR!
