### ISSUE TITLE
Consider adding async Executor to GatewayEndpointSpec

### ISSUE THREAD

**Issue by sirimamilla** [spring-projects/spring-integration#3165]
**Affects Version(s):** 5.2.3

---
Consider adding async Executor to GatewayEndpointSpec & GatewayMessageHandler.

Underlying GatewayProxyFactoryBean supports async Executor.

This will give developer to ensure gateway doesn't wait indefinitely for long running underlying threads.

**Comment by artembilan** [comment]
That's not how it works.

The "async Executor" has an effect only if:
```
if (this.asyncExecutor != null && !Object.class.equals(returnType)) {
			Invoker invoker = new Invoker(invocation);
			if (returnType.isAssignableFrom(this.asyncSubmitType)) {
				return this.asyncExecutor.submit(invoker::get);
			}
			else if (returnType.isAssignableFrom(this.asyncSubmitListenableType)) {
				return ((AsyncListenableTaskExecutor) this.asyncExecutor).submitListenable(invoker::get);
			}
			else if (CompletableFuture.class.equals(returnType)) { // exact
				return CompletableFuture.supplyAsync(invoker, this.asyncExecutor);
			}
			else if (Future.class.isAssignableFrom(returnType) && logger.isDebugEnabled()) {
				logger.debug("AsyncTaskExecutor submit*() return types are incompatible with the method return " +
						"type; running on calling thread; the downstream flow must return the required Future: "
						+ returnType.getSimpleName());
			}
		}
```

In other words when a return type of the gateway method is something like `Future`.

In case of a `GatewayMessageHandler` we don't have such a return type because we don't allow to provide a custom service interface. We configure a gateway proxy only with a `RequestReplyExchanger`, which contract is:
```
Message<?> exchange(Message<?> request) throws MessagingException;
```

So, I find this request a wrong one and fully not related to the current contract on the `GatewayEndpointSpec` & `GatewayMessageHandler`.

You should consider to break a dead lock some other way in the downstream on that `gateway()`.

**Comment by sirimamilla** [comment]
Seems like I missed some link. I will recheck and get back to you.

**Comment by sirimamilla** [comment]
Closing this as non issue
