### ISSUE TITLE
Resolved parameters not working if annotations are in superclass

### ISSUE THREAD

**Issue by jmaister** [spring-projects/spring-integration#3177]
I want to specify the annotations "@Payload" and "@Headers" in the "receive" method in the super class (i.e. BusinessLogic), so the implementation classes (i.e. BusinessLogicImpl) do not have to specify them.

However this example does not work like that, the method BusinessLogicImpl.receive gets as parameters the ConversionRequest instance and as a second parameter a Map with the payload as key-value pairs instead of a Map with the headers key-value pairs.

If I specify the annotations in the BusinessLogicImpl.receive method, it works as expected.

Question:
Should it work only if annotations are specified in super class (bug) or it is a must to define the annotations on every method (as it work now)?

Sample code:

    public abstract class BusinessLogic {
        /**
         * Receive from channel.
         */
        public abstract void receive(@Payload ConversionRequest input, @Headers Map<String, Object> headers);
    }

    @Component
    public class BusinessLogicImpl extends BusinessLogic {
        /**
         * Receive from channel.
         */
        @Override
        public void receive(ConversionRequest input, Map<String, Object> headers) {
            // Implementation ...
        }
    }

    /**
     * IntegrationFlow to receive messages from channel.
     */
    @Bean
    @Qualifier("SourceConvertRequestIntegrationFlow")
    public IntegrationFlow getSourceConvertRequestIntegrationFlow(BusinessLogic componentInterface) {
        return IntegrationFlows.from(channels.input())
            .handle(componentInterface, "receive", e -> e.advice(requestErrorsAdvice()))
            .get();
    }

**Comment by artembilan** [comment]
It cannot be treated as a bug because we never advertised such a feature with interfaces.
So, you should follow and existing behavior for some time, while I'm gathering more information what and how we support in other Spring projects.
I don't close the issue because it sounds reasonable, but at the same time I can't promise a solution if it cannot be possible with our annotation processing.

**Comment by jmaister** [comment]
I've been investigating a bit about this.

I was expecting the same behavior as using @Entity or @Controller at class level, where the implementing classes inherit them, however it does not work the same at parameter level:

From the @java.lang.annotation.Inherited annotation:

`Note that this meta-annotation type has no effect if the annotated type is used to annotate anything other than a class`

So that, getParameterAnnotations() does not get them

    // org.springframework.integration.handler.support.MessagingMethodInvokerHelper.HandlerMethod#generateExpression
    Annotation[][] parameterAnnotations = method.getParameterAnnotations();

**Comment by artembilan** [comment]
Well, what I see it is implemented as a custom logic for Spring MVC and only for interfaces:
```
	@Override
		public Annotation[] getParameterAnnotations() {
			Annotation[] anns = this.combinedAnnotations;
			if (anns == null) {
				anns = super.getParameterAnnotations();
				int index = getParameterIndex();
				if (index >= 0) {
					for (Annotation[][] ifcAnns : getInterfaceParameterAnnotations()) {
						if (index < ifcAnns.length) {
							Annotation[] paramAnns = ifcAnns[index];
							if (paramAnns.length > 0) {
								List<Annotation> merged = new ArrayList<>(anns.length + paramAnns.length);
								merged.addAll(Arrays.asList(anns));
								for (Annotation paramAnn : paramAnns) {
									boolean existingType = false;
									for (Annotation ann : anns) {
										if (ann.annotationType() == paramAnn.annotationType()) {
											existingType = true;
											break;
										}
									}
									if (!existingType) {
										merged.add(adaptAnnotation(paramAnn));
									}
								}
								anns = merged.toArray(new Annotation[0]);
							}
						}
					}
				}
				this.combinedAnnotations = anns;
			}
			return anns;
		}
```

See `org.springframework.web.method.HandlerMethod.HandlerMethodParameter` in `spring-web`.
It is not implemented for super classes and not in `spring-messaging`. 
So, I would say we have to stick with an existing behavior to make it as explicit in parameter parts as possible.
Plus it will be consistent everywhere in Spring where we deal with messages.

**Comment by jmaister** [comment]
When using a MessagingGateway and Gateway annotations, the Payload and Headers are defined in the interface and not in the implementation (as the implementation is hidden):

    @MessagingGateway
    public interface ConverterGateway {
        @Gateway(requestChannel = "internal_converter")
        void send(@Payload SingleValueMessage output);

        // SingleValueMessageHeaders extends HashMap
        @Gateway(requestChannel = "internal_converter")
        void send(@Payload SingleValueMessage output, @Headers SingleValueMessageHeaders headers);
    }

Looks like it is inconsistent to me, even if it is an interface or a superclass.

**Comment by artembilan** [comment]
Yeah... Unfortunately, you don't compare apples with apples. The `MessagingGateway` is fully based on the interfaces and it is exactly its feature to build a logic on the annotations from the interface methods and their parameters. There is really just no any implementation of the provided interface, so we do processing only from the interface. And behavior is exactly opposite: you say with that interface what to build when you call such a method before sending a message. With a `ServiceActivator` a logic is fully opposite: the framework call your method implementation and we really need an info for building arguments from the method signature.

Sorry, but I have to reject your argument because it doesn't fit to a subject we discuss here.
And I fully believe that we need to rely on exact method to call, not its super state. So, for the proper logic it is recommended to provide parameter annotations on the exact implementation. That's what I see here and everywhere else in Spring projects where the framework calls target project methods.

**Comment by jmaister** [comment]
OK, that makes sense.
Thanks for reviewing this issue.

**Comment by artembilan** [comment]
Closed as "Works as Designed"
