### ISSUE TITLE
Implement Channel Adapters for Redis Streams

### ISSUE THREAD

**Issue by akuma8** [spring-projects/spring-integration#3226]
It's a reminder of that JIRA issue: https://jira.spring.io/browse/INT-4567
I currently need this feature in my project and I don't see how to implement it easily. 
I can contribute with a little guidance since I never contributed to SI before.
Thanks

**Comment by artembilan** [comment]
See `StreamOperations` in Spring Data Redis and respective documentation: https://docs.spring.io/spring-data/redis/docs/2.3.0.M4/reference/html/#redis.streams

Also see https://spring.io/projects/spring-kafka for the Spring API around Apache Kafka. Don't confuse yourself with Kafka Streams though, because it looks like Redis Streams is more like regular Kafka Consumer/Producer.
There is also https://github.com/spring-projects/spring-integration-kafka project - Spring Integration channel adapter implementations around  Spring Kafka abstractions.

So, the goal of this issue is to have channel adapter implementations around Spring Data `StreamOperations` API.

Does it make sense?

Thank you for willing to contribute the feature!

**Comment by akuma8** [comment]
@artembilan Thank you for these details. I take a look about the implementation, I'll let you know if I need other information.
