### ISSUE TITLE
[RSocket] How to get a connection/session object in Request/responses and Request-Stream routes ?

### ISSUE THREAD

**Issue by LifeIsStrange** [spring-projects/spring-integration#3251]
**Describe the bug**

for example, in request/response mode:
```kotlin
@MessageMapping("foo")
    fun foo(): Mono<String> {
    // how to get an object that represent the current ConnectedClientSession ?
        return Mono.just("bar")
  }
```
We want to have a stateful user session management in order to be able to get on each *route* a session ID that would allow us to retrieve associated user metatada business logic.

How can this be achieved with RSocket ?
I believe that in websocket we could just have had a websocketSession object (or eventually used spring session).

Because we can't find a solution, we are thinking of creating a user sessionId on the client side instead and to periodically delete the sessionIds (because we can't with 100% success detect deconnexion in request response (e.g the user PC shut down). This workaround sounds like a complex, avoidable hack.

Rsocket seems to have the required primitive (even if an annotation and getting the session object in route parameter would be cleaner IMHO): ServerRSocketMessageHandler.getClientRSocketRequester(Object key)
But we can't figure out how this is supposed to be used. Can this be used inside a controller route to get the current Client session object (RSocketRequester) ? If so why should we input a key and where does this key come from ?

There is setClientRSocketKeyStrategy(java.util.function.BiFunction<Map<String,Object>,DataBuffer,Object> clientRSocketKeyStrategy) but we fail to understand how it should be used.

One could say this should be asked on Stackoverflow but I strongly feel that the documentation here isn't clear enough for mortals, and the guides lack examples.

**To Reproduce**
Not applicable because we actually fail to *produce*

**Expected behavior**
A clear undertandable documented solution for this very common problem

**Sample**
We do not have specificities, we are using lastest spring boot + RSocket + RSocket integration + Reactor + Kotlin (but a java solution would be fine)

**Comment by LifeIsStrange** [comment]
We have found that putting a RSocketRequester as a parameter is auto-injected by spring and through RSocketRequester.hashcode() allow us to have a unique sessionId !

@MessageMapping("foo")
    fun foo(request: RSocketRequester): Mono<String> {
        prinltn(request.hashcode())
        return Mono.just("bar")
  }

I find it weird that we have a RSocketRequester (the same object being used in the client)
I understand that it represent the client, but its weird that the RSocketRequester on the server still has ClientSide only methods ? (such as .route() ) or Am I misunderstanding something ?

Anyway the issue seems resolved ( so whats the utility of .getClientRSocketRequester(Object key) ?) 

Thanks anyway !

**Comment by artembilan** [comment]
Thank you for raising such a concern!

I definitely would say that this really belongs to StackOverflow or some other chat.
Feels like there is some inter-project misunderstanding:
1. `@MessageMapping` and its RSocket support belongs to Spring Framework project. Spring Integration provides channel adapter to send and receive messages over RSocket. It does nothing with `@MessageMapping`.
Therefore you might better to go to Spring Framework docs for understanding that `RSocketRequester` part on the server side: https://docs.spring.io/spring/docs/5.2.5.RELEASE/spring-framework-reference/web-reactive.html#rsocket-requester-server

2. You are missing an RSocket conceptual feature about `requester/responder` (See the same Spring Framework docs) :
> Once the initial connection is made, the "client" vs "server" distinction is lost as both sides become symmetrical and each side can initiate one of the above interactions. This is why in the protocol calls the participating sides "requester" and "responder" while the above interactions are called "request streams" or simply "requests". 

So, it doesn't matter what side you implement you still need an `RSocketRequester` to send to some `route` on the other side. But since we are talking about a server side it is indeed not a surprise that we can have several connected clients therefore we are going to have many  `RSocketRequester` instances - per connected client. It is fully clear in Spring Framework with `@MessageMapping` because we only have one method to get a request and produce replies. With Spring Integration it is slightly different - the flow might be much longer than one method. That's why curry an `RSocketRequester`  in the `RSocketRequesterMethodArgumentResolver.RSOCKET_REQUESTER_HEADER` header (Although it is done in Spring Framework  as well).

You probably may consider to rely on the `RSocketConnectedEvent` instead of `getClientRSocketRequester(Object key)` API. However the final clients mapping logic might be just the same: you map them yourself or you use a `setClientRSocketKeyStrategy()` on the `ServerRSocketMessageHandler`...

Please, let us know what you would like to have improved and we will reopen this issue accordingly or will raise a new one in Spring Framework if the concern belongs over there.
