### ISSUE TITLE
Aggregator - Capability to cache dynamic group timeout value

### ISSUE THREAD

**Issue by arajitsamanta** [spring-projects/spring-integration#3303]
**Expected Behavior**
When trying to figure out dynamic group timeout system would have the capability to cache the result of a method(user defined function) for the last message in a group in a `#variable`

Add a capability to add the last message as a `#variable` so that result can be cached for  
#variable so we can cache the current max timeout for each group and avoid iterating over the messages every time.

**Current Behavior**
When using `org.springframework.integration.expression.FunctionExpression` to determine dynamic group timeout(max timeout for the current group) it was observed that Function#apply() was invoked more than once for group. 

Here is an example how data looks like..
```
Group-1
 Request1-1 : timeout 1sec
 Request1-2 : timeout 2sec
Group-2
 Request1-1 : timeout 3sec
 Request1-2 : timeout 1sec
 Request1-3 : timeout 5sec
``` 
In this example for group1, function gets invoked 2 times, for group 3 it gets invoked 3 times.

Had a chat with @garyrussell on this and figured that it was designed in that way i.e every time a new message added to the group, it will try to figure out timeout invoking `Function#apply()` when using `FunctionExpresssion`

System wont go over iterating all the message in a group for every invocation of function.
**Context**

**Comment by garyrussell** [comment]
My suggestion [here]( https://gitter.im/spring-projects/spring-integration?at=5ee145ce7c64f31f11528a4e) was that we could (optionally) add `#lastMessage` as a variable to the evaluation context to avoid having to iterate over the entire list.

We should also consider adding some kind of user-state to the message group (but that would be more invasive and probably a 5.4-only feature.

**Comment by arajitsamanta** [comment]
I agree @garyrussell . I updated original post as per your suggestion. let me know if there is anything incorrect in my feature request. I can update if needed.

**Comment by garyrussell** [comment]
No; it's fine; thanks; I just wanted to add a link to the gitter discussion.

Bear in mind that this feature will require switching to a propert SpEL expression rather than a `FunctionExpression`; something like:

```
"@someBean.someMethod(#root, #lastMessage)"
```

and

```java
public long someMethod(MessageGroup group, Message<?> lastmessage) { ... }
```

**Comment by garyrussell** [comment]
Another alternative would be to add `getLast()` to `MessageStore`.

**Comment by artembilan** [comment]
After some brief chat with Gary we came to the solution like this which is going to work even right now.

The `AbstractBatchingMessageGroupStore` can be configured with the custom `MessageGroupFactory` which could produce a custom `MessageGroup`.
with its `add(Message<?> messageToAdd)` you can calculate whatever you need over the group and store in the group property.
This custom `MessageGroup` may have a getter for that property, so in your `Function` for a `groupTimeout` you can cast a `group` argument to your custom `MessageGroup` and get access to that property with no iteration over the whole group content.

See more info in the docs: https://docs.spring.io/spring-integration/docs/current/reference/html/system-management.html#message-group-factory

Unfortunately your use-case is not so common to be added into the framework as an out-of-the-box feature and probably ever `getLast()` may not be enough everywhere.
With the custom `MessageGroup` you have a freedom to do whatever complex logic should be done around group content.

Let us know if that makes sense to you and we will close this as `Won't Fix` since there is a solution even if it is more involved than restricted `#variable` solution...

Thanks for understanding!

**Comment by arajitsamanta** [comment]
@artembilan Above suggested solution would work in my case as it seems developers would have more control over messages being added in the group. 

I do understand my requirement(dynamic group timeout)  is not a very common use case. Most of the time group timeout would a static value configured as application startup time.

Thanks you for all of your help and suggestions!!
