### ISSUE TITLE
Add server url property to MqttIntegrationEvent

### ISSUE THREAD

**Issue by Happy-Neko** [spring-projects/spring-integration#3340]
**Expected Behavior**
`MqttIntegrationEvent` should have `server` property or other means to find what MQTT server caused it.

**Current Behavior**
`MqttIntegrationEvent` does not have `server` property.

**Context**
I have multiple inbound MQTT adapters connected to different servers. Right now it is impossible to find what server caused  application event. For example `MqttConnectionFailedEvent` may not have any mentions of failed server depending on type of the underlying exception.

`AbstractMqttMessageDrivenChannelAdapter.getUrl()` is protected. Also I am not sure if it is set correctly if urls are configured through `MqttConnectOptions`. At the very least `AbstractMqttMessageDrivenChannelAdapter` should log server url on errors.

**Comment by artembilan** [comment]
The `MqttIntegrationEvent` is supplied with a `source` which is essentially a channel adapter caused such an event.
We probably need to introduce something like `MqttClientAccessor` to implement in all the MQTT channel adapters and give access from there to `serverURIs` array. We might deprecate that `protected String getUrl()` since Paho client really operates over the array of uris - an explicit or provided via `MqttConnectOptions.getServerURIs()`.

This way the source of the event could be cast to that type via `EventObject.getSource()` and you'll get access to that URIs option.

We probably indeed should enhance that 
```
logger.error("Error connecting or subscribing to " + Arrays.toString(topics), e);
```
to include some connection information as well.

@garyrussell , any thoughts?

**Comment by Happy-Neko** [comment]
> This way the source of the event could be cast to that type via `EventObject.getSource()` and you'll get access to that URIs option.

May be override `MqttIntegrationEvent.getSource()` to `public MqttClientAccessor getSource()` to avoid client-side cast?

**Comment by garyrussell** [comment]
>@garyrussell , any thoughts?

I concur with both suggestions.

Yes, we could narrow the `getSource()` return type, or add another getter.

**Comment by artembilan** [comment]
> Yes, we could narrow the getSource() return type, or add another getter.

We removed that downcast in the past because of classes tangle...

**Comment by garyrussell** [comment]
Oh, right, yes, of course; I added the following to `KafkaEvent` to make it a bit more user friendly...

```
	/**
	 * Get the container (source) that published the event. This is provided as an
	 * alternative to {@link #getSource()} to avoid the need to cast in user code. The
	 * type is required here to avoid a dependency tangle between the event and listener
	 * packages.
	 * @param type the container type (e.g. {@code MessageListenerContainer.class}).
	 * @param <T> the type.
	 * @return the container.
	 * @see #getContainer(Class)
	 * @see #getSource()
	 * @since 2.2.1
	 */
	@SuppressWarnings("unchecked")
	public <T> T getSource(Class<T> type) {
		Assert.isInstanceOf(type, getSource());
		return (T) getSource();
	}
```

We could also add

```java
public <T> T getClient() { }
```

And the compiler can infer the type

```java
MqttClientAccessor accessor = event.getClient();
```
