### ISSUE TITLE
Fluent API Enhancement for CharacterStreamWritingMessageHandler

### ISSUE THREAD

**Issue by nikhilvasaikar** [spring-projects/spring-integration#3343]
**Expected Behavior**

It would be nice to have a fluent way of setting the shouldAppendNewLine for `CharacterStreamWritingMessageHandler`
Something like `CharacterStreamWritingMessageHandler.stdout().appendNewLine()`

**Current Behavior**

`.handle(CharacterStreamWritingMessageHandler.stdout())`

**Context**

As a workaround, create the instance and call the setter as seen below:
```
@Bean
public IntegrationFlow receiveGreetingFromGreetingQueueToConsole(ConnectionFactory connectionFactory) {

    CharacterStreamWritingMessageHandler stdout = CharacterStreamWritingMessageHandler.stdout();
    stdout.setShouldAppendNewLine(true);
    return IntegrationFlows.from(Amqp.inboundAdapter(connectionFactory, "greeting.queue"))
            .log()
            .<String,String>transform(m -> "Received " + m)
            .handle(stdout)
            .get();

}
```

**Comment by garyrussell** [comment]
@artembilan I don't think it's worth creating a DSL spec for this component, there is only one setter; I think we can just add a fluent API method 

`CharacterStreamWritingMessageHandler.addNewLine()`.

WDYT?

**Comment by artembilan** [comment]
Yes, no problem with that `appendNewLine()` fluent API. It is kinda the same setter, but with returning an instance.

I recall as I had a discussion with Juergen about XML parser to make them to understand builder pattern where that fluent API can be treated as setters. The answer was that it is going to be tough to change that infrastructure since it is fully tied into Java Beans introspection logic. But I know for sure that fluent setters works well in XML. Although they sound awkward when you type Java configuration 😄
