### ISSUE TITLE
How to give the different topic name in @InboundChannelAdapter?

### ISSUE THREAD

**Issue by vishnu2497** [spring-projects/spring-integration#3442]
Hi Guys

In spring integration i am using `@InboundChannelAdapter` 

 ```
@InboundChannelAdapter(channel = "myowntopic")
    public MessageSource<List<String>> addProducts() {
        List<Product> products = Stream.of(new Product(101, "Mobile", 8000)
                , new Product(102, "book", 6000))
                .collect(Collectors.toList());
 return () -> MessageBuilder.withPayload(sss).build();
```

if i use topic name as **`OUTPUT`** it is working as expected ,

but if i use any other topic it wont accept those values and application is throwing error to create a bean.

Topic name is just a String we need any bean for that?

```
APPLICATION FAILED TO START
***************************
Description:

A component required a bean named 'myowntopic' that could not be found.

Action:

Consider defining a bean named 'myowntopic' in your configuration.

```

Am i doing correctly?

**Comment by garyrussell** [comment]
GitHub issues are NOT for asking questions; use stack overflow (or the Discussions tab here on GitHub) for questions.

The channel must exist.

If you are using Spring Cloud Stream - with `EnableBinding(Source.class)`, the channel `Source.OUTPUT` is automatically created by the framework; that's why it works.

To use a different name, you need to replace the `Source` interface with your own, with an appropriately named channel.

If this doesn't answer your question, ask on Stack Overflow, tagged with `spring-integration` showing much more detail.
