### ISSUE TITLE
MessageProducerSupport loses exception on application shutdown

### ISSUE THREAD

**Issue by elefeint** [spring-projects/spring-integration#3450]
**In what version(s) of Spring Integration are you seeing this issue?**
5.3.0.RELEASE, although this would manifest in any version from the last couple of years.

**Describe the bug**
Upon application context shutdown, `BroadcastingDispatcher`'s list of `MessageHandler`s is cleared. This in itself is not a problem; however it causes [this block](https://github.com/spring-projects/spring-integration/blob/0331933c168f9096195999592a7f169d39f238d2/spring-integration-core/src/main/java/org/springframework/integration/endpoint/MessageProducerSupport.java#L210-L214) in `MessageProducerSupport` to lose the exception.

**To Reproduce**

The downstream manifestation on Cloud Pub/Sub implementation of `MessageProducerSupport` was reported by a user in spring-cloud/spring-cloud-gcp#2615 as unexpected acknowledgment of an known bad message (message handling code explicitly throws a `RuntimeException`) when application was shutdown midway through processing. The example can be found in https://github.com/thayhoang/pubsub-demo; however it requires a working GCP Cloud Pub/Sub setup. In this particular case, the application is a Spring Cloud Stream sink, and the difference between the correct scenario (when exception bubbles up to the binder correctly) and the incorrect one (when, after application context shutdown, the binder completes successfully) is the presence or absence of `org.springframework.cloud.stream.binder.FinalRethrowingErrorMessageHandler`.

I've also put together a [unit test demonstrating the issue](https://github.com/elefeint/spring-integration/commit/3bb1d49f025919b5fe9ab5bc88c1208170b29496). the setup is not ideal because it manually unsubscribes the error channel and stops the `MessageProducerSupport`, but it shows both the problem and the potential fix.

**Expected behavior**

Exception from message handlers should always be propagated upstream, unless properly handled by the error handler. Missing error handler and/or known context shutdown should not be considered handled and should instead result in exception propagation.

**Sample**

[Unit test](https://github.com/elefeint/spring-integration/blob/3bb1d49f025919b5fe9ab5bc88c1208170b29496/spring-integration-core/src/test/java/org/springframework/integration/endpoint/MessageProducerSupportTests.java#L123-L165)

[Proposed fix](https://github.com/elefeint/spring-integration/blob/3bb1d49f025919b5fe9ab5bc88c1208170b29496/spring-integration-core/src/main/java/org/springframework/integration/endpoint/MessageProducerSupport.java#L211-L215)

**Comment by artembilan** [comment]
Happy New Year, @elefeint !

Thanks for the report, but this is indeed an expected behavior with any `PublishSubscribeChannel`, where a default global `errorChannel` is an instance of it.
The logic there is like this (in the `BroadcastingDispatcher`):
```
if (this.requireSubscribers && handlers.size() == 0) {
	throw new MessageDispatchingException(message, "Dispatcher has no subscribers");
}
```
Since `requireSubscribers` is `false` by default and when we stop an application context, all the subscribers are gone, so we just ignore that message and drop it silently.

We probably need to think broader and really make a default `errorChannel` with that `requireSubscribers = true` to have an exception thrown instead of fixing lifecycle for just a `MessageProducerSupport`. Even if that is going to be a `MessageDispatchingException` instead of an original send error, we still going to have that info in the failed message. Plus, I think, it won't matter for GCP to nack the message in the topic for the future consideration when consumer is back.

So, if you agree (CC @garyrussell ), that the problem is much broader than just `MessageProducerSupport` and it is better to always throw something from an error channel, I would suggest a fix like a `requireSubscribers` property on the `PublishSubscribeChannel` and make it as a `true` by default for a global default `errorChannel` in the current `5.5` and let end-user to configure it in the previous version to avoid a breaking change. We probably may consider to introduce an integration property like `spring.integration.channels.error.requireSubscribers=true|false` for easier end-user experience with such a migration to different default behavior for global `errorChannel`: https://docs.spring.io/spring-integration/reference/html/configuration.html#global-properties

**Comment by garyrussell** [comment]
Yes; I think that solution makes sense; it shouldn't cause any real problems because the default `errorChannel` always gets one subscriber.

However, it won't solve the problem in the binder because the message producer gets a binding-specific error channel (which is bridged to the global error channel), so we'd need a similar change there.

**Comment by artembilan** [comment]
Right. That was my idea with an exposing that option, so we can fix Spring Cloud Stream to never lose the message and throw it as an error at least back to the binder.

Unfortunately the logic in the `DefaultConfiguringBeanFactoryPostProcessor.registerErrorChannel()` says slightly different, Gary:

```
BeanDefinitionBuilder loggingEndpointBuilder =
	BeanDefinitionBuilder.genericBeanDefinition(ConsumerEndpointFactoryBean.class)
					.addPropertyReference("handler", errorLoggerBeanName)
					.addPropertyValue("inputChannelName", IntegrationContextUtils.ERROR_CHANNEL_BEAN_NAME);
```
that means that this endpoint is going to be stopped and, therefore, unsubscribed from the `errorChannel` when we shutdown an application context. Not sure if we can change that behavior since that `_org.springframework.integration.errorLogger` endpoint has been here from day first...

**Comment by garyrussell** [comment]
I am not sure what you mean by "slightly different". 

Yes, I know the logging handler will be unsubscribed when the context is stopped; I meant it won't cause a problem in a running application since there will always be this one subscriber.

The only behavior difference is the no subscribers exception will be thrown if an error occurs during shutdown, which I don't think is a big problem.

**Comment by artembilan** [comment]
Well, I think this is exactly a situation we have here: the message producer consumes a message and sends it downstream for processing. At this moment a shutdown happens and this producer is stopped to not consume more messages. But at the same time a stop signal is propagated to all our endpoints. If any exception happens in the handler, it is thrown back to the producer and there is an attempt to handle that exception in the `errorChannel` flow. And since we've got a stop already, there is no any subscribers on this error channel to handler such an `ErrorMessage`. Therefore we lose it silently and don't allow to nack on the broker.

With a `requireSubscribers=true` we never lose the message and, at least, log it under `error` when we throw a `MessageDispatchingException` upstream from that unsubscribed error channel independently of the application state.

**Comment by garyrussell** [comment]
Exactly; we are on the same page; as I said initially

>Yes; I think that solution makes sense; ...

**Comment by elefeint** [comment]
Sorry, just noticed the waiting-for-reporter tag :) Yes, I think the more general solution of requiring at least one subscriber on an error channel would be great. Thanks for thinking about the broader problem!
