### ISSUE TITLE
Polling 0 messages per run

### ISSUE THREAD

**Issue by bojanv55** [spring-projects/spring-integration#3464]
Current code that is doing polling has this code:

```
private Runnable createPoller() {
		return () ->
				this.taskExecutor.execute(() -> {
					int count = 0;
					while (this.initialized && (this.maxMessagesPerPoll <= 0 || count < this.maxMessagesPerPoll)) {
						if (pollForMessage() == null) {
							break;
						}
						count++;
					}
				});
	}
```

Should this `this.maxMessagesPerPoll <= 0` be actually `this.maxMessagesPerPoll < 0`, since I wanted to control this parameter in the runtime, but cannot set 0 to pause polling for a while. I know that I can change polling interval which would have more/less same effect, but this setting I also think does not work as it should. Was this on purpose or?

**Comment by artembilan** [comment]
It was like that from day first and it really looks like an intention to treat `0` as a infinite messages request as well.
On the other hand this option was not designed to be changed at runtime.

I think we can relax the current behavior and really consider to treat this option more broader especially when we talk about a reactive mode for this kind of endpoints...

We probably also need to log some warn message that no polling attempts are going to be performed since max is `0`. Implementation details though - not important at the moment.

With new `0` for `maxMessagesPerPoll` we probably can all consider to implement `Pausable` contract for the `AbstractPollingEndpoint`.

WDYT, @garyrussell ?

In regards to pausing, @bojanv55 , I think you need  to take a look into `stop()/start()` hooks of that `AbstractPollingEndpoint` to ensure that you don't poll at some specific moment and then you restart later on. See Control Bus about management commands: https://docs.spring.io/spring-integration/reference/html/system-management.html#control-bus

**Comment by bojanv55** [comment]
So `maxMessagesPerPoll` should not be changed in runtime? Or it was just not intended to be used in that way? I would like to use this since it fits perfectly for my needs. But then I will also have to take a look at start()/stop() unless you upgrade to support 0 in some of the next versions.

**Comment by artembilan** [comment]
That's right. We got your request - will have a team discussion.
Anyway this probably can make it on into the next `6.0` version.

**Comment by bojanv55** [comment]
One question related to this - I saw in the code that long time ago you changed 

```
					long nanos = TimeUnit.MILLISECONDS.toNanos(timeout);
					long deadline = System.nanoTime() + nanos;
					while (this.queue.size() == 0 && nanos > 0) {
						this.queueSemaphore.tryAcquire(nanos, TimeUnit.NANOSECONDS); // NOSONAR - ok to ignore result
						nanos = deadline - System.nanoTime();
```

to

```
					Message<?> message = this.queue.poll();
					if (message == null) {
						long nanos = TimeUnit.MILLISECONDS.toNanos(timeout);
						long deadline = System.nanoTime() + nanos;
						while (message == null && nanos > 0) {
							this.queueSemaphore.tryAcquire(nanos, TimeUnit.NANOSECONDS); // NOSONAR ok to ignore result
							message = this.queue.poll();
							if (message == null) {
								nanos = deadline - System.nanoTime();
							}
						}
					}
					return this.queue.poll();
					return message;
```

Now, since I'm using statefull poller, each time it polls it increases internal counter. Here with the new code it calls .poll() method twice and it advances mu internal index by 1. So if I use `Pollers.fixedDelay(5, TimeUnit.SECONDS, 5).maxMessagesPerPoll(1)` having in mind single poll and index increment per 5 seconds, it actually does this 2 times. And I guess, if I use `maxMessagesPerPoll(2)` - it will increase my internal index 4 times (since for every poll it is done twice). Is this possibly a bug?

**Comment by artembilan** [comment]
Well, you probably need to adjust the logic of your custom `Queue` to that double `poll()` call.
As you see it is fully not aware what you are doing in your own code. Our goal here is to ensure that we try to get a message during that `timeout` interval. So, probably better to say that bug is in your own code since you don't rely on the `if (message == null)` fact when you advance that index.

**Comment by bojanv55** [comment]
I'm just not sure why the call is there in the first place? If it was not polled on a first occasion, why try again? I mean, I would like it to try polling again, but that should be specified by `Pollers.fixedDelay(10, TimeUnit.MINUTES, 10)` and not to have framework try to poll "just in case".

My logic is pretty simple - I have 4 groups, and on each poll, I poll from 1 of the groups. If that group is empty, I advance to the next group. I would expect having `Pollers.fixedDelay(10, TimeUnit.MINUTES, 10)` to advance to next group every 10 minutes - but in this case it will poll twice - so it will also advance the group twice if empty.

Now all this is not a big deal, since I'm polling anyway 100 messages per second - so few more advances are not that important. Just wanted to know why it was done at the first place this way? Was there some threading issue or?

**Comment by artembilan** [comment]
OK. See the contract:
```
	/**
	 * Subclasses must implement this method. A non-negative timeout indicates
	 * how long to wait if the channel is empty (if the value is 0, it must
	 * return immediately with or without success). A negative timeout value
	 * indicates that the method should block until either a message is
	 * available or the blocking thread is interrupted.
	 * @param timeout The timeout.
	 * @return The message, or null.
	 */
	@Nullable
	protected abstract Message<?> doReceive(long timeout);
```

So, what we do there in the `pollNonBlockingQueue(timeout)` is just an attempt to reach the target `Queue` until it returns something or timeout expires. That is done because there is no way to propagate a timeout to non-blocking queue, e.g. JDBC-backed `MessageStore`. Well, that's why it is non-blocking though... Previously it was based on the `size()` call as you pointed to the commit and that was really a performance degradation. Therefore we decided to change it to `poll()` call in a `while()` loop. 

I don't know exact your logic in your custom `Queue`, but there is no other way then trying to follow our contract in the `QueueChannel`. 

And as I said you on StackOveflow, it might be better to look into a  custom `expireMessageGroups(long timeout)` implementation for your aggregator instead of a custom queue for aggregation and so.

**Comment by bojanv55** [comment]
OK, so this code looks like simulating blocking with artificial timeout on non-blocking queue. Shouldn't you have split logic for blocking/nonblocking queues in the first place...

Is this part of contract fulfilled for nonblocking? - `A negative timeout value indicates that the method should block until either a message is available or the blocking thread is interrupted.` - since negative value here will just skip (I guess it is not easy to simulate this).

In the end - just one more question - how `size()` call was performance degradation, since I guess it is just one integer get and compare operation? That call seems to be better here for me, since it is idempotent (comparing to poll which is expected to have side effects).

**Comment by artembilan** [comment]
> Shouldn't you have split logic for blocking/nonblocking queues in the first place...

Well, I think every software suffer from some refactoring from time to time. So, it was designed only for `BlockingQueue` in the beginning, then someone reported a wish to have a `QueueChannel` against non-blocking queue and so on.

>  since negative value here will just skip 

Not sure what you mean. We simulate negative timeout via infinite loop in the `doReceive()`:
```
else {
		Message<?> message = this.queue.poll();
		while (message == null) {
			this.queueSemaphore.tryAcquire(50, TimeUnit.MILLISECONDS); // NOSONAR ok to ignore result
			message = this.queue.poll();
		}
		return message;
}
```
>since I guess it is just one integer get and compare operation

Looks like you just didn't follow all the links from the mentioned commit:
https://github.com/spring-projects/spring-integration/issues/2628

Probably you better to revise your solution based on the `BlockingQueue`...

**Comment by bojanv55** [comment]
Yeah, just saw that infinite loop...

Have not read all the commit details. Anyway I can use it this way also - not a big deal for me.

**Comment by artembilan** [comment]
See also Migration Guide note: https://github.com/spring-projects/spring-integration/wiki/Spring-Integration-5.4-to-5.5-Migration-Guide#0-for-maxmessagesperpoll
