### ISSUE TITLE
Exception in AggregatorFactoryBean.processorBean not noticed by Spring Retry if MessageGroup is partially released

### ISSUE THREAD

**Issue by adixkeindl** [spring-projects/spring-integration#3559]
My Setting:
- Spring Cloud Data Flow (App Version 2.7.1, Helm Chart 2.7.3) 
- using Kafka with enabled DLQ 
- spring-integration-core-5.2.6.RELEASE

The Processor component:
Processor Class is doing aggregation using AggregatorFactoryBean. 
- The AggregatorFactoryBean.processorBean throws an exception, e.g.:
```
public class AggregatingMessageGroupProcessor extends AbstractAggregatingMessageGroupProcessor  {
    protected final Object aggregatePayloads(MessageGroup group, Map<String, Object> headers) {
        throw new RuntimeException("some error");
    }
}
```

- AggegationFactoryBean.groupTimeoutExpression is something small so that a MessageGroup definetly will be expired and a partially complete group will be released, e.g. 1000

- The AggregatorFactoryBean.releaseStrategy is MessageCountReleaseStrategy with some high threshold, e.g 500 so that MessageCountReleaseStrategy.canRelease won't return true before timeout occurs.

Now the first message will be processed. In AbstractCorrelatingMessageHandler.processMessageForGroup MessageCountReleaseStrategy.canRelease is false so the group will be scheduled for force complete. A ScheduledFuture is created which will check the timeout for the MessageGroup. Timeout occurs because of our setting above and MessageGroup will be force completed. The AggregatorFactoryBean.processorBean will be processed and the exception is thrown.

This exception which is thrown in a scheduledFuture thread gets lost. Spring Retry isn't aware of it and therefore no message is created for the DLQ. 

If the MessageCountReleaseStrategy.threshold is 1 and no ScheduledFuture is created to check the timeout, then the exception is thrown in the main thread so that Spring Retry get notice of it and a message is created for the DLQ.

**Comment by artembilan** [comment]
Not sure what is the questions though?
It is really expected that `groupTimeout` operation happens on a scheduled thread and everything what you have configured for a main flow thread is not going to be taken into account.

That's why we have introduced a `setForceReleaseAdviceChain(List<Advice> forceReleaseAdviceChain)` on the `AggregatorFactoryBean`. See docs for more info: https://docs.spring.io/spring-integration/docs/current/reference/html/message-routing.html#aggregator

> Since version 4.1.
It allows the configuration of any `Advice` for the `forceComplete` operation.
It is initiated from a `group-timeout(-expression)` or by a `MessageGroupStoreReaper` and is not applied to the normal add, release, and discard operations.
Only this sub-element or `<expire-transactional/>` is allowed.
A transaction `Advice` can also be configured here by using the Spring tx namespace.

One of that `Advice` indeed can be a `RetryOperationsInterceptor` with an appropriate `MethodInvocationRecoverer` to deliver unprocessed messages to some DLQ or so.

It is probably not possible to do that customization for existing `aggregator-propcessor` to make it working in the SCDF, but you definitely can build your own to meet expectation.

Does it make sense?

**Comment by adixkeindl** [comment]
Hi, thanks. I'll read the doc and give it try.
