### ISSUE TITLE
Gradle Module Metadata for spring-integration-bom 5.4.7 missing from Maven Central

### ISSUE THREAD

**Issue by fpavageau** [spring-projects/spring-integration#3570]
**In what version(s) of Spring Integration are you seeing this issue?**

5.4.7 (also present in 5.5.0)

**Describe the bug**

[`spring-integration-bom-5.4.7.pom`](https://search.maven.org/artifact/org.springframework.integration/spring-integration-bom/5.4.7/pom) was generated with the following comment

```xml
<!-- This module was also published with a richer model, Gradle metadata,  -->
<!-- which should be used instead. Do not delete the following line which  -->
<!-- is to indicate to Gradle or any Gradle module metadata file consumer  -->
<!-- that they should prefer consuming it instead. -->
<!-- do_not_remove: published-with-gradle-metadata -->
```

which triggers the download by Gradle of the `spring-integration-bom-5.4.7.module` artifact, however that artifact was not published to Maven Central. This is probably a consequence of an upgrade to Gradle 6.

This is a problem when using Artifactory as a Maven proxy, because by default Artifactory returns a 403 HTTP status code for missing artifacts, and Gradle only ignores an absent `.module` when the repository returns a 404 HTTP status code. In my case (and others, probably), that means my build fails when it cannot download `spring-integration-bom-5.4.7.module`. 😭

See
- rsocket/rsocket-java#746 resolved by rsocket/rsocket-java#751
- remkop/picocli#1152 resolved by [`0874760`](https://github.com/remkop/picocli/commit/0874760e7caa5616dec3318515583b78105e92ab)

for similar issues in other projects that have bit me in the past (through spring-boot-dependencies).

**Expected behavior**

It would be good if either the module file was published on Maven Central, or the Gradle metadata generation was disabled.

**Comment by artembilan** [comment]
Well, what I see the `.module` files are present when I install artifacts locally. For example this is a content for `5.5.0-SNAPSHOT`:
```
{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.integration",
    "module": "spring-integration-bom",
    "version": "5.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.2",
      "buildId": "64x7ex4b4jh3vomm7mg3j3kjqm"
    }
  },
...
```

And so on for all the modules we have in the project.
So, this is indeed not a Gradle or Artifactory.
Here is its presence in our, Spring repository: https://repo.spring.io/libs-release-local/org/springframework/integration/spring-integration-bom/5.5.0/spring-integration-bom-5.5.0.module.

The problem comes with Maven Central sync: it just does not allow to upload non-matching artifacts.

As long as we all rely on Maven Central and since all other projects just ignore those artifacts, we are going to disable such a feature the way you suggest.

Let me know if you can contribute the fix: https://github.com/spring-projects/spring-integration/blob/main/CONTRIBUTING.adoc

Thank you!

**Comment by fpavageau** [comment]
There you go: #3571.

Should I create similar pull requests for the `5.4.x` and `5.3.x` branches?

**Comment by artembilan** [comment]
Thanks.

No, you don't need. We will review shortly and just cherry-pick your commit to those supported branches!
