### ISSUE TITLE
Add Support for Spring AMQP 2.4

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-integration#3584]
Make spring-integration-amqp compatible with both spring-amqp 2.3.x and 2.4.x.

**Comment by artembilan** [comment]
Fixed via: https://github.com/spring-projects/spring-integration/commit/76f77ccd2c5f94e000495357e66c4f99fffc6010

**Comment by ae-govau** [comment]
Since updating to Spring Boot 2.5.3 (which bumps 5.5.1 to 5.5.2) one of our apps fails to start and report this error message:

```
Description:
An attempt was made to call a method that does not exist. The attempt was made from the following location:
     org.springframework.cloud.stream.binder.rabbit.RabbitMessageChannelBinder.createConsumerEndpoint(RabbitMessageChannelBinder.java:517)
The following method did not exist:
     'void org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter.<init>(org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer)'
```

I suspect that's related to this change?

I note the following related JARs in our app, each of which appear to be latest.

```
BOOT-INF/lib/spring-integration-amqp-5.5.2.jar - contains AmqpInboundChannelAdapter.class
BOOT-INF/lib/spring-cloud-stream-binder-rabbit-3.1.3.jar - contains RabbitMessageChannelBinder.class
```

I find the layout of the Spring projects quite complex so I'm not sure where best to report this issue, but figured I'd start here since I think this likely introduced the problem.

**Comment by artembilan** [comment]
That’s correct : we did it here. We just missed the fact that Rabbit Binder is not going to release until September as a part of Spring Cloud release. See this issue for workaround for time being : https://github.com/spring-projects/spring-integration/issues/3601. Sorry for inconvenience

**Comment by ae-govau** [comment]
Thanks @artembilan :+1:
