### ISSUE TITLE
AmqpInboundChannelAdapter.<init>(Lorg/springframework/amqp/rabbit/listener/AbstractMessageListenerContainer;)V

### ISSUE THREAD

**Issue by ASanny** [spring-projects/spring-integration#3601]
When the spring-boot-starter-parent version is 2.5.3, the introduction of spring-cloud-starter-bus-amqp will lead to this problem. The constructor of AmqpInboundChannelAdapter exists in the version 5.5.1 spring-integration-amqp , but not exist in the version 5.5.2. Who can correct it? Thank you

**Comment by mmaeller** [comment]
I got the same issue.

**Comment by mmaeller** [comment]
In my case, I tracked the issue down to https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/blob/main/spring-cloud-stream-binder-rabbit/src/main/java/org/springframework/cloud/stream/binder/rabbit/RabbitMessageChannelBinder.java#L517
That's the reason for the exception.
Looks like this commit caused the issue 
https://github.com/spring-projects/spring-integration/commit/76f77ccd2c5f94e000495357e66c4f99fffc6010

**Comment by artembilan** [comment]
Spring Integration has already released all the versions to make it compatible with the latest Spring AMQP.
`5.5.2` has made it into Spring Boot `2.5.3`; `5.4.9` is going to be included into Boot `2.4.10` on August 19th.

There is nothing more we can do from this project perspective.
Apparently we must fix something on RabbitMQ Binder side: https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/issues/328. Probably just recompile it against latest Spring Integration.
I'm closing this one in favor of that since it really feels more lie fix needed to be done there, but not here.

Thanks for understanding!

Meanwhile I just repeat myself here for better visibility since you might not be last who faces the same issue.
So, to bring it back for working version, you just need to override Spring Integration version in your POM until the next Spring Cloud RabbitMQ Binder (or Bus) release.
See Boot docs on the matter: 
https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using.build-systems.dependency-management
https://docs.spring.io/spring-boot/docs/2.5.3/maven-plugin/reference/htmlsingle/#using.parent-pom
Therefore this is what you need in your POM:
```
<properties>
    <spring-integration.version>5.5.1</spring-integration.version>
</properties>
```

**Comment by ASanny** [comment]
OK, thank you for your help

**Comment by artembilan** [comment]
Reopen since I found the fix to bring byte code compatibility back.

**Comment by walfom** [comment]
发给对方法国大使法国  饿哦佛 地方
