### ISSUE TITLE
Need for fast Java Collections

### ISSUE THREAD

**Issue by hubertpnj** [spring-projects/spring-integration#3633]
You all use default Java Collections, although they have unnecessary features like mod count, please use fast personalized Collections.

**Comment by artembilan** [comment]
Since this sounds more like a language level request (even not Spring Core one) and this doesn't follow our [Feature Request template](https://github.com/spring-projects/spring-integration/blob/main/.github/ISSUE_TEMPLATE/feature_request.md) and does not have any perfromance reports to justify a change and find this as non-relevant and close as `Invalid`.
