### ISSUE TITLE
Resolve deprecations in spring-integration-kafka after upgrade to Spring for Apache Kafka 2.8/30

### ISSUE THREAD

**Issue by artembilan** [spring-projects/spring-integration#3661]

**Comment by artembilan** [comment]
Need also to figure out what to do with already deprecated `org.springframework.kafka.listener.adapter.RetryingMessageListenerAdapter` in the `KafkaMessageDrivenChannelAdapter`

**Comment by 50qbits** [comment]
Hello, I've found that KafkaMessageListenerContainerSpec.errorHandler is using GenericErrorHandler and this is deprecated in favor of DefaultErrorHandler (since spring-kafka 2.8).

Besides spring-kafka ConcurrentKafkaListenerContainerFactory and KafkaMessageListenerContainer.setErrorHandler​(ErrorHandler errorHandler) is deprecated in favor of setCommonErrorHandler(CommonErrorHandler)

Any plans to updated this before 6.0.x?

**Comment by garyrussell** [comment]
I have almost completed the PR. It should be posted today and will be in the next milestone.
