### ISSUE TITLE
Setting metadatakey on FeedEntryMessageSource using URL object is appending url to metadatakey but when Resource object is used, only metadatakey is set

### ISSUE THREAD

**Issue by pinkeshsagar-harptec** [spring-projects/spring-integration#3735]
**Using spring integration core 5.5.7 and spring integration feed 5.5.7**

**Expected Behavior**

If user is already passing metadatakey then he is already aware about metadatakey, so both constructors of FeedEntryMessageSource should only set metdatakey, not modify it.

**Current Behavior**

Currently, if object of FeedEntryMessageSource created with URL, then url is appended with metadatakey and if created with second constructor which takes Resource then it is only setting metadatakey.

**How has this issue affected you?**
I am creating instance of FeedEntryMessageSource with both constructors. so if instance with URL failed then Resource one can be used but i am getting different metadatakey in both cases.

What other alternatives have you considered? None

Are you aware of any workarounds? No

**Comment by artembilan** [comment]
It was like that `this.metadataKey = metadataKey + "." + feedUrl;` from a day first, long before we had introduced a `Resource`.
Since we are in major release phase at the moment, I think it is good time to make that breaking change and really fully only on the provided `metadataKey` only.

Feel free to contribute the fix: https://github.com/spring-projects/spring-integration/blob/main/CONTRIBUTING.adoc.

Thank you!
