### ISSUE TITLE
Feature Request - doOnNext()

### ISSUE THREAD

**Issue by ipanimnim** [spring-projects/spring-integration#3780]
**Expected Behavior**
I'd like to be able to easily write code that is equivalent to:
```java 
writeToFoo();
writeToBar();
```
Project Reactor did a good job in this subject, creating the `.doOnNext()`, that lets me write:
```java 
flow
 .doOnNext(writeToFoo())
 .doOnNext(writeToBar());
```

**Current Behavior**
In Spring Integration, to perform this basic operation, one needs to configure an executor, and use `publishSubscribeChannel`, and write:
```java
      .publishSubscribeChannel(s -> s
              .subscribe(f -> f
                      .handle(writeToFoo()))
              .subscribe(f -> f
                      .handle(writeToBar())));
```
This is redundant and scary (the word subscribe is pretty confusing here. I don't want to publish or subscribe. I want to do something after another, without consuming the last or something). I think Spring Integration should have an equivalent method with the same name.

**Context**
[This issue talked about this.](https://stackoverflow.com/questions/71618148/reactive-spring-integration-equivalent-to-project-reactor-doonnext)

**Comment by ipanimnim** [comment]
@artembilan WDYT?

**Comment by artembilan** [comment]
I think the `doOnNext()` operator in Reactor was not designed for the service calls like you show.
I believe the `flatMap()` with `then()`, or `join()`, or `concat()`, or even `merge()` is the way to call services sequentially and in reactive manner.

The `doOnNext()` is like `peek()` in Java streams. The analog in Spring Integration Java DSL is a `wireTap()` or just `intercept()`.
So, if you wish you can write something like:

```
flow
    .wireTap(sf -> sf.handle(writeToFoo()))
    .wireTap(sf -> sf.handle(writeToBar()))
```

I recommend to use a `publishSubscribeChannel()` because this is exactly a proper Enterprise Integration Pattern to distribute the same message to several services: https://www.enterpriseintegrationpatterns.com/patterns/messaging/PublishSubscribeChannel.html.
The wire-tap (or as your said `doOnNext()`) is not a proper way for message streaming when we want to deal with some service activators.

If you still wish to use a `doOnNext()`, you can look into already mentioned not one time `fluxTransform()` operator which purpose is indeed to inject a `Flux` processing inside an `IntegrationFlow`:
```
flow
    .fluxTransform(flux -> flux
                          .doOnNext(writeToFoo())
                          .doOnNext(writeToBar()))
```

If you still insist on the fist class `IntegrationFlow` operator like this `doOnNext()`, you can take a look into an `IntegrationFlowExtension` and write your own operator, which might be based on the `wireTap()` sub-flow or so: https://docs.spring.io/spring-integration/docs/current/reference/html/dsl.html#java-dsl-extensions.

Nevertheless my answer is "No" for this issue: the `doOnNext()` is not for service calls in Reactor, neither `wireTap()` in Spring Integration. 
The messaging and proper distribution into endpoints via channels is a top priority of Spring Integration framework as it is aimed for a canonical support of the EIP.
Everything else which may even look convenient is out of scope of our responsibility and has to be handled other way.

Closing as `Won't Fix`

**Comment by artembilan** [comment]
If you wish to simulate a `doOnNext()` from the Reactor, then you don't need an executor for the `publishSubscribeChannel()` and both calls are going to happen on the same thread. Just like it is done with those fused  `doOnNext()`!
