### ISSUE TITLE
Update Documentation for JUnit5

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-integration#3787]
For example https://docs.spring.io/spring-integration/docs/current/reference/html/testing.html#test-context shows `@RunWith(SpringRunner.class)`.

There may be others.

**Comment by artembilan** [comment]
Turns out that there is only one of this in the docs and there is no more "hard" requirements for JUnit 4, so I decided to include the fix into my current PR #3792 .
I guess we will keep mentioning of the JUnit 4 rules in the docs until its EoL.

I don't see a hard reason to back-port this into `5.5.x`...
