### ISSUE TITLE
Gateways created using DSL nondeterministically aren't available in the context

### ISSUE THREAD

**Issue by chrylis** [spring-projects/spring-integration#3922]
**In what version(s) of Spring Integration are you seeing this issue?**

5.5.14

**Describe the bug**

I am using the Java DSL to define interface-based gateways. Nondeterministically, the application fails with a `NoSuchBeanDefinitionException`. In particular, the problem seems to be related to the build JVM; I am having consistent success with ecj and AdoptOpenJDK-11.0.11+9 (using the identical `./mvnw package` as on CI), but running the jar downloaded from CI (AdoptOpenJDK (build 11+28)) fails with an identical environment. With the CI jar,

```
2022-10-20T19:48:45,344Z [main] WARN  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: 
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'directDelivery' defined in class path resource [com/example/application/IntegrationConfig.class]:
  Unsatisfied dependency expressed through method 'directDelivery' parameter 0; nested exception is
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'whatsAppDelivery' defined in class path resource [com/example/lib/autoconfigure/DependencyAutoConfiguration.class]:
  Unsatisfied dependency expressed through method 'whatsAppDelivery' parameter 3; nested exception is
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.example.api.Updater' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
```

The bug _feels_ like there's some nondeterministic ordering of dependency resolution. I have read the reference documentation but am unclear on how an `IntegrationFlow` bean is transformed into the appropriate business interface for purpose of bean resolution.

**To Reproduce**

```
interface Updater { void update(Foo foo) }

class WhatsAppDelivery {
  @Autowired Updater updater
}

@Configuration
@Import(WhatsAppDelivery)
class IntegrationConfig {
  @Bean
  IntegrationFlow directDelivery(WhatsAppDelivery whatsapp) {
    IntegrationFlows.from(CHANNEL_DELIVERY_WHATSAPP)
      .handle(whatsapp, 'deliver')
      .transform(Try::get)
      .get()
  }

  @Bean
  IntegrationFlow updater() {
    IntegrationFlows.from(Updater)
      .channel(CHANNEL_UPDATE)
      .get()
  }
}
```

**Expected behavior**

I expect that at every application launch, a bean of type `Updater` will be available in the context.

**Comment by garyrussell** [comment]
In my experience, you need to add `@DependsOn("updater")` (e.g. on `directDelivery`) to force the creation of gateway proxy during the creation of that bean.

Without that, Spring has no idea that `directDelivery` depends on `updater`.

**Comment by chrylis** [comment]
I note that I omitted the intermediate bean (expressed in the error message) that has a known dependency on `Updater` (the type).

The purpose of the `Updater` interface is to decouple the module that consumes it (by sending back updates) from the configuration that defines it (in this case, via Spring Integration). Using `@DependsOn` would put that explicit coupling right back; in addition, I interpret your comment to mean that gateway proxies defined using the Spring Integration DSL will not correctly/reliably trigger Spring Boot auto-configuration `ConditionalOnBean`, which makes Boot or Spring Integration an either/or choice.

**Comment by garyrussell** [comment]
No. It is simply that instantiating the updater bean will create the proxy. There is nothing the DSL or Spring can do to ensure that it is created first because there is no hard implicit dependency, it needs some help.

Making the updater factory method `static` might work, if you don’t want to use `@DependsOn`.

**Comment by chrylis** [comment]
If I understand correctly, Boot auto-configuration would need to understand the (future) presence of the `Updater` bean to process `ConditionalOnBean`, but it can't "see" it because its horizon is limited to the signature of the `@Bean IntegrationFlow` method. Is this correct?

**Comment by garyrussell** [comment]
It has nothing to do with Boot. It is normal Spring bean dependency. If Spring knows bean A depends on bean B, or some downstream B dependency, it will instantiate B first. If it does not know about the relationship, as in this case, the instantiation order is indeterminate.

**Comment by artembilan** [comment]
The problem this an `IntegrationFlow` and its content via builder that it is processed a bit later in a configuration phase than it would give us a hint about possible dependencies expose.
It might be even better to think about an `IntegrationFlow` as a black box and don't expect anything from it to be public available.

One of the workaround is to have a `@DependsOn("updater")` as Gary already pointed. Technically you still have that dependency via `Updater` injection, so adding one more hint to is not so bad.
It is really something similar what you suggest with that `@ProvidesBean` in SF.

Another workaround, which is more Spring idiomatic is to declare an `Updater` interface as a top-level component - `@MessagingGateway`.

One more time: the `IntegationFlow` must be considered as a black-box for configuration and we must not expect from it too much for the whole dependency injection infrastructure.
Also see that `@DependsOn` JavaDocs:

```
 * Beans on which the current bean depends. Any beans specified are guaranteed to be
 * created by the container before this bean. Used infrequently in cases where a bean
 * does not explicitly depend on another through properties or constructor arguments,
 * but rather depends on the side effects of another bean's initialization.
```

> side effects of another bean's initialization

That is exactly what we have with that `from()` for the `IntegrationFlow` bean definition.

And that's why an `IntegationFlow` is so flexible in a way that it can be configured not on the fly but with predefined beans.

I guess this issue will be addressed as a doc to mention such a limitation with an `IntegrationFlow` bean content and dependency injection  expectations and why the `@DependsOn` can be used to mitigate an immediate concern.

Does it make sense for you?

**Comment by chrylis** [comment]
> It has nothing to do with Boot. It is normal Spring bean dependency. If Spring knows bean A depends on bean B, it will instantiate B first. If it does not know about the relationship, as in this case, the instantiation order is indeterminate.

Auto-configuration is solved in a separate step, so even an instantiation sequence that will work with an unconditional dependency may fail to resolve the auto-configuration conditions even without the dynamic-bean-provider aspect.

> It might be even better to think about an IntegrationFlow as a black box and don't expect anything from it to be public available.

This makes sense given how it operates, but there's an impedance mismatch between the DSL's concepts and how the context bean resolution functions.

> Technically you still have that dependency via Updater injection, so adding one more hint to is not so bad.

I have a dependency _on an interface_ but not on a specific bean-by-name.

> Does it make sense for you?

I understand the technical problem, but a more-elegant long-term solution would still be ideal. I have two ideas, based on the concept that the fundamental problem is that the context can't see the dynamically-created beans:

1. Allow the `IntegrationFlow` builder DSL to return either a `MyGateway` or a `Provider/Supplier<MyGateway>` as a terminal step, permitting the `@Bean` method return type to indicate the gateway type that will be registered.
2. Provide programmatic access to be able to explicitly expose the gateway beans as independent `@Bean`s, with perhaps something like this:
   ```
   // somewhere else there is an `IntegrationFlows.from(MyGateway.class)`

   @Bean
   MyGateway myGateway(IntegrationContextThing ic) {
     return ic.getGateway(MyGateway.class);
   }
   ```

**Comment by artembilan** [comment]
See my answer to your SO thread: https://stackoverflow.com/questions/74158211/is-there-a-directive-to-individually-import-a-spring-integration-gateway-in-java.
Instead of trying to invent something new which does not justify its narrow specifics, it is better to design a "component first" in mind, then connect everything in the `IntegrationFlow`.

And no, the `IntegrationFlow` cannot expose such a type since it is really not its responsibility. From my point of your it would be something similar to what you said about a `@DependsOn` - the expose concern which does not belong to an `IntegrationFlow` purpose.

**Comment by chrylis** [comment]
I think I have a clearer understanding of the interaction constraints between the Spring Integration proxy and the overall context now. I have some ideas for possible improvements (and I plan to experiment with a `BeanFactoryPostProcessor` to see if I can make one work), but at the current moment this effect is an unavoidable circumstance based on the various features involved.
