### ISSUE TITLE
spring-integration-jdbc 5.2.x distributed lock method tryLock (long time, TimeUnit unit) invalid

### ISSUE THREAD

**Issue by EverSpring** [spring-projects/spring-integration#3992]
**version**: 
5.2.X
**the bug**
Two distributed services are deployed. When `tryLock (long time, TimeUnit unit)` is used, the lock will be obtained at the same time, but `tryLock()` or `lock()` are normal

**To Reproduce**
1. the server
```
@Resource
private LockRegistry lockRegistry;

Lock lock = lockRegistry.obtain(lockKey);
boolean acquired;
try {
	acquired = lock.tryLock(1,TimeUnit.SECONDS);
} catch (Exception e) {
	log.error("", e);
}
if (acquired) {
	try {
		log.info("acquire key:{}", lockKey);
		ThreadUtils.sleep(10000L);
	} finally {
		lock.unlock();
	}
}
```
2. the client
```
ExecutorService executorService = Executors.newFixedThreadPool(3);
int cnt = 6;
int[] port = {10097, 10003};
CountDownLatch countDownLatch = new CountDownLatch(cnt);
for (int i = 0; i < cnt; i++) {
	executorService.execute(() -> {
		String randomString = RandomUtil.randomString(6);
		int randomPort = port[RandomUtil.randomInt(0, 2)];
		log.info("request port:{},randomString:{}", randomPort, randomString);
		String s = HttpUtil.get("http://localhost:" + randomPort + "/demo/spring-lock/1", CharsetUtil.CHARSET_UTF_8);
		log.info("get data:{}", s);
		countDownLatch.countDown();
	});
}
try {
	countDownLatch.await(30, TimeUnit.SECONDS);
} catch (InterruptedException e) {
	e.printStackTrace();
}
````

**Expected behavior**
Only one process can acquire the lock

**Comment by EverSpring** [comment]
**jdbc config**
```
@Slf4j
@Configuration
public class JdbcLockConfig {
    @Bean
    public JdbcLockRegistry jdbcLockRegistry(DataSource dataSource) {
        DefaultLockRepository lockRepository = new DefaultLockRepository(dataSource, "test-lock");
        lockRepository.setPrefix("T_DISTRIBUTE_");
        lockRepository.setTimeToLive(10000);
        lockRepository.afterPropertiesSet();
        return new JdbcLockRegistry(lockRepository);
    }
}
```

**Comment by artembilan** [comment]
First of all `5.2.x` is AOL already: https://spring.io/projects/spring-integration#support.
Consider to upgrade to the latest version: https://spring.io/projects/spring-integration#learn.

Second: it is not recommended to use a static shared `clientId` for `DefaultLockRepository`: only really when several instances of your application are still treated as a single one.
It is hard to reproduce with your code snippets since not fully clear what you are doing. 
I only can guess that you start several web application on different ports in that `int[] port = {10097, 10003};` range.

Please, consider to upgrade, use random `clientId` and then share with us a simple project (or unit) test we can reproduce and confirm easily.

Thanks for understanding.

**Comment by EverSpring** [comment]
Yes, I understand the `DefaultLockRepository` `clientId` incorrectly. Thank you very much!
