### ISSUE TITLE
TcpOutboundGateway. Semaphore not released after exception

### ISSUE THREAD

**Issue by opardor** [spring-projects/spring-integration#3993]
Hello, I have found next behaviour which could be an issue.

I'm working around with the HelloWorldInterceptor example, a TcpOutboundGateway in async mode and a ConnectionFactory with singleUse=false field. 

In this test the Server is who should start the handshake conversation. 
Once the client tries to send a message it waits for hello" message from the server, if the await time expires it throws a MessagingException (negotiation error); then the exception is catched by TcpOutboundGateway, and cleanup method in finally block is not invoked so semaphore is not released and next invocations to handleMessage are locked (until request timeout passed) when acquiring the semaphore.

Attached proofOfConcept and test execution log.

[Git proofOfConcept](https://github.com/opardor/spring-tcp-demo)
[test.log](https://github.com/spring-projects/spring-integration/files/10453822/test.log)

**Comment by artembilan** [comment]
There is no server implementation in your project.
Please, consider to create some GitHub repository to share with us where we can run and reproduce.
For now I have to implement the server side myself, although it is fully unclear what it may look like.


Then I look into your logs and see this relevant stack trace:
```
org.springframework.messaging.MessagingException: Negotiation error
	at com.poc.tcpclient.HelloWorldInterceptor.send(HelloWorldInterceptor.java:101) ~[classes/:na]
	at org.springframework.integration.ip.tcp.TcpOutboundGateway.handleRequestMessage(TcpOutboundGateway.java:226) ~[spring-integration-ip-5.5.13.jar:5.5.13]
```

The related code is like this: https://github.com/spring-projects/spring-integration/blob/main/spring-integration-ip/src/main/java/org/springframework/integration/ip/tcp/TcpOutboundGateway.java#L210-L251.

So, with a high speculation I can guess what is going on with this analysis:
1. The `acquireSemaphoreIfNeeded()` returns `true` because the mentioned `singleUse=false` configuration.
2. We create an `AsyncReply` to wait for `onMessage()`.
3. We fail on the `connection.send(requestMessage);` because there is no answer from the server for handshake.
4. Therefore we never reach 
```
		if (isAsync()) {
			reply.getFuture().set(message);
			cleanUp(reply.isHaveSemaphore(), reply.getConnection(), connectionId);
		}
```
in the `TcpOutboundGateway.onMessage()` to release that `semaphore`.
5. And we cannot release in the `TcpOutboundGateway.handleRequestMessage()` `finally` block because that one is only for `sync` cases.

So, if this is what you really see, then I'll fix it respectively.
Not sure yet for unit test should do, but this is definitely a bug.

Thank you!

**Comment by opardor** [comment]
Hi! Your speculation is right.
I've created a repository where you can reproduce the exception, also removed the attached zip from the original comment.

[https://github.com/opardor/spring-tcp-demo](https://github.com/opardor/spring-tcp-demo)
