### ISSUE TITLE
filter namespace parser should allow multiple child selector namespace objects [INT-1085]

### ISSUE THREAD

**Issue by spring-operator** [spring-projects/spring-integration#5090]
**[aappddeevv](https://jira.spring.io/secure/ViewProfile.jspa?name=aappddeevv)** opened **[INT-1085](https://jira.spring.io/browse/INT-1085?redirect=false)** and commented

Currently, the filter namespace parser allows bean or poller as child elements. It should also allow selector namespace specifications. Since the selector namespace creates a MessageSelector object already, it would just allow a namespace way of specifying the selectors. The selector children should be allowed to be a list and perhaps a filter attribute decides between an AND or OR application to the selectors. The workaround is to build a filter chain or to specify the filter objects through their bean class names directly.

---
No further details from [INT-1085](https://jira.spring.io/browse/INT-1085?redirect=false)

**Comment by artembilan** [comment]
The `<filter>` component has these options `<filter ref="" method="" expression="">`, which are fully enough to cover all the possible complex (AND/OR) logic without extra XML tags in the config.

Similar applies to the `@Filter` endpoint on a POJO method or Java DSL with a `filter()` configuration.

Therefore closed as `Won't Fix` since an XML config should not turn into a programming language.
