### ISSUE TITLE
RabbitMQ quorum queue support for MQTT

### ISSUE THREAD

**Issue by ibnuShahar** [spring-projects/spring-integration#8567]
**Expected Behavior**

Spring Integration for MQTT inbound/outbound adapters/gateways exposes methods to declare queue type as quorum.

**Current Behavior**

Default MQTT queue created is always classic queue.

**Context**

RabbitMQ is scheduling to remove classic queue in their future releases. Spring Integration with AMQP allows us to add property  x-queue-type = quorum to our Queue definition which causes RabbitMQ to create a new quorum queue. 

Is there any plan to support this behavior for MQTT?

**Comment by garyrussell** [comment]
Spring does not “declare” queues for MQTT, the infrastructure is created by their plug-in. This question should probably be directed to the RabbitMQ team and their MQTT plug-in. Try the rabbitmq-users Google group.

**Comment by artembilan** [comment]
This is indeed out this project scope: you always can create RabbitMQ objects some other way, not relying on topic auto-creation when we use them from MQTT channel adapters.
On the other hand, if they remove classic queue support, then by default it is going to be the mentioned quorum queues.
Therefore we still don't need to do anything on our side since auto-created MQTT topics are going to be based on the mentioned quorum by default.
If it is not the case, then I don't see a reason in removing classic queue support.

Closed as `Not planned`.
