### ISSUE TITLE
JsonToObjectTransformer looses timestamp of original message

### ISSUE THREAD

**Issue by joshiste** [spring-projects/spring-integration#8756]
**In what version(s) of Spring Integration are you seeing this issue?**

For example:

6.0.6

**Describe the bug**

When a message is transformed using the JsonToObjectTransformer the TIMESTAMP header of the original message is not kept and a new one is generated.

**Expected behavior**

Only transformation of the payload. Keeping the headers.

Should it use the MutableMessageBuilder instead?

**Comment by mrpiggi** [comment]
Well, you could achieve this with
```java
JsonToObjectTransformer jsonToObjectTransformer = new JsonToObjectTransformer();
jsonToObjectTransformer.setMessageBuilderFactory(new MutableMessageBuilderFactory());
```

**Comment by joshiste** [comment]
Ah yes you're right. I basically gave the answer in the request. Was maybe too obvious for me 😂

**Comment by artembilan** [comment]
The default `GenericMessage` is immutable object. Therefore changing anything with it would lead to a new instance.
Every instance has its `id` and `timestamp`, so it is not a surprise that every Spring Integration endpoint returns a new message when it does something with payload or headers.

If you really would like to keep original message metadata, then yes, the `MutableMessageBuilderFactory` is the way to go, as @mrpiggi has pointed.

However the `MutableMessage` must be used with caution: in most cases we got a gain from messaging that it is stateless. Therefore changes in one place don't effect others which might be performed in parallel.
With `MutableMessage` we got an object which has a state and one thread making changes to this message may effect others.
There is also a side-effect when it is hard to trace what is going with messages because there is just one of them.

We introduced this `MutableMessage` abstraction for limited number of use-case: where you really don't care about messaging, but benefit from Spring Integration API and channel adapters catalog.
