### ISSUE TITLE
Option to configure WebClient dynamically via an Expression or Function in WebFluxMessageHandlerSpec

### ISSUE THREAD

**Issue by syedyusufh** [spring-projects/spring-integration#8900]
Please provide an option to configure `WebClient` dynamically via an `Expression` or `Function` in `WebFluxMessageHandlerSpec`

Currently `WebFluxMessageHandlerSpec` supports `Expression` / `Function` for URI, HttpMethod. 

Use-case for the above request is based on a header value need to use plain `WebClient` or `WebClient` with `Proxy` configuration.

Thanks

**Comment by artembilan** [comment]
I'm going to be very reluctant to make this possible since it opens a can of worms to give the application a chance to fail with some vulnerability or so when we resolve such an service from expression.

Right now you can go ahead with couple `handle(WebFluxMessageHandlerSpec)` definitions and determine which to use via `route()`.
The `WebClient` is a `final` required property of the `WebFluxRequestExecutingMessageHandler`.
It is going to be a bit involving to redo it to be resolved at runtime against message.
However I would try to stay away from such an approach where we got an easier solution with controlled configuration via router.

WDYT?

**Comment by syedyusufh** [comment]
Thanks @artembilan for the quick revert. I agree with you and it makes sense. Let me take the `route()` 👍
