### ISSUE TITLE
WebFlux inboundGateway with custom replyChannel is failing to send the response if headers are copied from the failedMessage

### ISSUE THREAD

**Issue by syedyusufh** [spring-projects/spring-integration#9227]
`WebFlux.inboundGateway` with custom `replyChannel` is failing to send the response if headers are copied from the failedMessage. This behavior is observed with **Spring Boot v3.3.0**

Please try the sample project to understand more on the problem,

https://github.com/syedyusufh/webflux-inboundgateway-error.git

Same works fine if the headers are copied from the current message.

**Comment by artembilan** [comment]
Please, share some instructions how to try your app?
Do we really need all those deps to reproduce the problem?
And how does it fail, please?

**Comment by syedyusufh** [comment]
Sorry, please make a POST Request as below to trigger a validation failure

http://localhost:8080/testapp/testuri

{ "firstName1": "Name1", "lastName": "Name2" }


there won't be any response sent back for the inboundGateway, whereas it will work fine if the current message's headers are copied instead of the failedMessage's.

**Comment by artembilan** [comment]
So, if you fix your code just to this:
```
.transform(Message.class, m -> "API Failed")
```
it works as expected.

The problem here that we are in the error handling sub-flow which expects a reply on its own `replyChannel` header.
Those headers from the `failedMessage` are obsolete for this sub-flow.
They may make sense if you handle error somewhere in the middle of the flow, but if you throw an exception back to the gateway, for its `.errorChannel(appErrorChannel)` , then you have to rely on headers exactly from the `ErrorMessage` processed in that error sub-flow.

Does that make sense?
Or would you expect some other behavior?

**Comment by syedyusufh** [comment]
Thanks for the detailed explanation. Could you please help me understand how was it working before then which you had helped us asking to map the `replyChannel` from the failedMessage.

https://stackoverflow.com/questions/75109345/spring-integration-webflux-inboundgateway-replychannel-for-error-response

**Comment by artembilan** [comment]
Well, this scenario for `.errorChannel(appErrorChannel)` didn't work even before.
Have just downgraded your project to Spring Boot `3.2.6` - same behavior.
I see different headers in debug, therefore my explanation still stays for older versions as well: the error flow from inbound gateway has its own `replyChannel`.

**Comment by syedyusufh** [comment]
Thanks @artembilan , it is working as expected then.
