### ISSUE TITLE
Adding Mqttv5PahoMessageDrivenChannelAdapter to running Mqttv5ClientManager

### ISSUE THREAD

**Issue by Ricore72** [spring-projects/spring-integration#9368]
version 6.3.1

**Description**
I want to add multiple instances of Mqttv5PahoMessageDrivenChannelAdapter (on demand, when application is running) using already running client in Mqttv5ClientManager as constructor parameter. When I try, it does not work. 
Cause seams to be MqttCallback:: connectComplete ,which sets the readyToSubscribeOnStart property.
That obviously cant trigger because client is already connected.

**To Reproduce**
1.	Create an instance of Mqttv5ClientManager
2.	Start clientManager
3.	create an instance of Mqttv5PahoMessageDrivenChannelAdapter with clientManager
4.	register adapter in IntegrationFlow using IntegrationFlowContext
5.	Try to send messages to it

**Possible Fix**
https://github.com/Ricore72/spring-integration
The fix does not work completely.

It only works if Handlers and adapters using same clientManager have the same Qos.

**Note** 
I am not sure if this is the proper way to do this. This is my first issue to public project. So sorry if it is incorrect in any way.

**Comment by artembilan** [comment]
It looks like the `ClientManager`  should expose an `isConnection()` API.
The problem is that your `ClientManager` has been started and connected.
So, all those dynamically added channel adapters at runtime just lose their `connectComplete()` callback.
Therefore in the `AbstractMqttMessageDrivenChannelAdapter.onInit()` we should check for the mentioned `ClientManager.isConnection()`  and set `readyToSubscribeOnStart = true`.
So, when this dynamic channel adapter is started it will understand that it is already OK to subscribe.

Feel free to play with that and contribute back: https://github.com/spring-projects/spring-integration/blob/main/CONTRIBUTING.adoc

Thank you!

**Comment by artembilan** [comment]
I changing this to `Enhancement` since we never advertised that such a scenario is supposed to work.
So, new feature for new version.
Will review your PR shortly.
Thanks
